/-
Copyright (c) 2026 Chris Brink. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Brink

# The music kernel "The Fifth" on `ℤ/12`, and the closure/escape dichotomy

Paper 1's music kernel is **The Fifth**; Paper 3 and the validation claim
`music-kernel-05-z12z-cycle.md` record a correction to an early LLM draft
that wrongly asserted an accumulation operator `D_12` satisfies
`D_12^12 = id`.  The corrected picture distinguishes two operations on
`ℤ/12` driven by the fifth (`+7`):

* **Translation** `T : x ↦ x + 7` genuinely returns to the identity after
  twelve steps (`fifth_returns`), and not before (`fifth_order_twelve`):
  the circle of fifths is a single 12-cycle visiting every pitch class
  (`fifth_orbit_covers`).
* **Accumulation** (the additive closure generated by the fifth) therefore
  *saturates* to all of `ℤ/12`: the subgroup generated by `7` is the whole
  group.

This is the precise sense in which the music kernel **closes in the
tempered quotient `ℤ/12`** — and it is exactly the complement of the
*rank-2 Diophantine floor* (`Examples/DiophantineFloor.lean`,
`rank_two_floor`): in the frequency-ratio domain the fifth `3/2` never
closes (`3^a ≠ 2^b` nontrivially), while in the equal-tempered quotient
`ℤ/12` it closes after twelve steps.  The Pythagorean comma is the gap
between these two facts — closure in `ℤ/12`, non-closure in `ℚˣ`.

All statements here are finite and discharged by `decide`.
-/
import Mathlib.Data.ZMod.Basic

namespace FalseWork.MusicKernel

/-- The perfect fifth as a translation on pitch classes: `+7` on `ℤ/12`. -/
def fifth (x : ZMod 12) : ZMod 12 := x + 7

/-- **The circle of fifths returns.**  Iterating the fifth twelve times is
the identity: twelve perfect fifths span seven octaves back to the start
(in the tempered quotient). -/
theorem fifth_returns : ∀ x : ZMod 12, fifth^[12] x = x := by decide

/-- **The fifth has order exactly twelve.**  No nonzero iterate before the
twelfth brings `0` back to `0`: the circle of fifths is a single 12-cycle,
not a shorter one. -/
theorem fifth_order_twelve :
    ∀ k : Fin 12, 0 < k.val → fifth^[k.val] 0 ≠ 0 := by decide

/-- **The circle of fifths covers all twelve pitch classes.**  Every pitch
class is reached from `0` by some number `< 12` of fifths — the additive
closure generated by the fifth saturates to all of `ℤ/12`. -/
theorem fifth_orbit_covers :
    ∀ p : ZMod 12, ∃ k : Fin 12, fifth^[k.val] 0 = p := by decide

/-- **The music kernel closes in the tempered quotient (bundled).**  On
`ℤ/12` the fifth is a single 12-cycle: it returns after twelve steps, not
before, and visits every pitch class.  This is the quotient-side closure
that the rank-2 Diophantine floor (`FalseWork.Diophantine.rank_two_floor`)
denies in the frequency-ratio domain — the two faces of the Pythagorean
comma. -/
theorem fifth_closes_in_quotient :
    (∀ x : ZMod 12, fifth^[12] x = x) ∧
    (∀ k : Fin 12, 0 < k.val → fifth^[k.val] 0 ≠ 0) ∧
    (∀ p : ZMod 12, ∃ k : Fin 12, fifth^[k.val] 0 = p) :=
  ⟨fifth_returns, fifth_order_twelve, fifth_orbit_covers⟩

end FalseWork.MusicKernel
