/-
Copyright (c) 2026 Chris Brink. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Brink

# The Nishimura normal form — Phase 1 (term closure)

This file is the active spine target registered at
`validation/claims/nishimura-normal-form.md`.  The goal of the full
development is to prove that the subalgebra generated by a single element
`g` of a Heyting algebra is exactly the **Rieger–Nishimura ladder** — the
set `{⊤} ∪ {nishimuraTerm g n : n}` of `NishimuraKernelLaw.lean`.  Proving
this discharges the one classical citation **[C]** still standing under the
all-`n` kernel law (`nishimura_kernel_unique`): the Nishimura enumeration
`hgen` becomes a Lean theorem rather than a quoted result, and the music
lattice's order-embedding (`div12OrderEmbedding`) upgrades to a *subalgebra*
embedding (Citkin's Prop. 3.1 in full).

**Phase 1 (this file, in progress).**  Closure of the ladder set under the
Heyting operations — the Rieger–Nishimura "tables" as derived identities.
This is the foundation for the structural induction that gives the normal
form.  Landed so far, all `sorry`-free:

* `IsLadderValue` and the basic memberships (`⊤`, `⊥`, the generator);
* the **complement table** `isLadderValue_compl`: `xₙᶜ` is again a ladder
  value (`⊤, x₃, x₁, x₁, ⊥` for `n = 0, 1, 2, 3, ≥ 4`);
* the **definitional diagonals** `nishimuraTerm_join_diagonal` /
  `nishimuraTerm_himp_diagonal`: the main diagonals of the join and
  implication tables, read straight off the term recursion (`xₙ₊₂ ⊔ xₙ₊₃ =
  xₙ₊₅` for `n` odd; `xₙ₊₃ ⇨ xₙ₊₂ = xₙ₊₅` for `n` even), with their closure
  corollaries.

Still open in Phase 1: the **off-diagonal** meet, join, and implication
entries (the genuine weeks-long core, by strong induction on the term
recursion). The certified-safe meet table on `x₀…x₆`, the literature Hasse
structure, and the collapse-artifact protocol are recorded in
`validation/claims/nishimura-normal-form.md`. Then Phases 2–4
(finite-truncation normal form, the abstract normal form discharging `hgen`,
and the `Div12` subalgebra upgrade).
-/
import Mathlib.Order.Heyting.Basic
import FalseWorkPapers.Examples.NishimuraKernelLaw

namespace FalseWork.Lattice

section NormalForm

variable {H : Type*} [HeytingAlgebra H]

/-- The **Rieger–Nishimura ladder values** in a generator `g`: `⊤` together
with the canonical term sequence `nishimuraTerm g n`.  The normal-form
theorem under construction is that this set is exactly the subalgebra
generated by `g`. -/
def IsLadderValue (g x : H) : Prop := x = ⊤ ∨ ∃ n : ℕ, x = nishimuraTerm g n

theorem isLadderValue_top (g : H) : IsLadderValue g ⊤ := Or.inl rfl

theorem isLadderValue_bot (g : H) : IsLadderValue g ⊥ :=
  Or.inr ⟨0, by simp [nishimuraTerm]⟩

theorem isLadderValue_gen (g : H) : IsLadderValue g g :=
  Or.inr ⟨2, by simp [nishimuraTerm]⟩

theorem isLadderValue_term (g : H) (n : ℕ) : IsLadderValue g (nishimuraTerm g n) :=
  Or.inr ⟨n, rfl⟩

/-! ### The complement table

In the Rieger–Nishimura ladder the complement of every term is again a
term: `x₀ᶜ = ⊤`, `x₁ᶜ = x₃` (`¬¬g`), `x₂ᶜ = x₁` (`¬g`), `x₃ᶜ = x₁`
(triple negation), and `xₙᶜ = ⊥ = x₀` for all `n ≥ 4`, because every such
term lies above `x₄ = ¬g ⊔ g`, whose complement is `⊥`. -/

/-- Every ladder term from index `4` on has complement `⊥`: it lies above
`x₄ = ¬g ⊔ g`, and `(¬g ⊔ g)ᶜ = ¬¬g ⊓ ¬g = ⊥`. -/
theorem compl_nishimuraTerm_ge_four (g : H) {n : ℕ} (hn : 4 ≤ n) :
    (nishimuraTerm g n)ᶜ = ⊥ := by
  have h4 : gᶜ ⊔ g ≤ nishimuraTerm g n := four_le_nishimuraTerm g n hn
  have hle : (nishimuraTerm g n)ᶜ ≤ (gᶜ ⊔ g)ᶜ := compl_anti h4
  rw [compl_sup] at hle
  have hz : gᶜᶜ ⊓ gᶜ = ⊥ := by rw [inf_comm]; exact inf_compl_self gᶜ
  rw [hz] at hle
  exact le_bot_iff.mp hle

/-- **Complement closure (the RN complement table).**  The complement of a
ladder term is again a ladder value. -/
theorem isLadderValue_compl (g : H) (n : ℕ) :
    IsLadderValue g (nishimuraTerm g n)ᶜ := by
  match n with
  | 0 => exact Or.inl (by simp [nishimuraTerm])
  | 1 => exact Or.inr ⟨3, by simp [nishimuraTerm]⟩
  | 2 => exact Or.inr ⟨1, by simp [nishimuraTerm]⟩
  | 3 => exact Or.inr ⟨1, by simp [nishimuraTerm]⟩
  | (k + 4) =>
      exact Or.inr ⟨0, by
        rw [compl_nishimuraTerm_ge_four g (by omega : 4 ≤ k + 4)]
        simp [nishimuraTerm]⟩

/-- Complement closure stated for the whole ladder set, `⊤` included
(`⊤ᶜ = ⊥`). -/
theorem isLadderValue_compl_of (g : H) {x : H} (hx : IsLadderValue g x) :
    IsLadderValue g xᶜ := by
  rcases hx with rfl | ⟨n, rfl⟩
  · exact Or.inr ⟨0, by simp [nishimuraTerm]⟩
  · exact isLadderValue_compl g n

/-! ### The definitional diagonals

The term recursion itself supplies the *main diagonals* of the join and
implication tables, with no order reasoning: for `n` odd the join of two
consecutive terms is the next term, and for `n` even the implication of two
consecutive terms is the next term.  These anchor the induction for the full
binary tables (the off-diagonal entries are the genuine work); see the
literature reference in `validation/claims/nishimura-normal-form.md`.

A caution recorded there: the finite truncations `Zₙ` collapse higher rungs, so
e.g. `Z₈` evaluates `x₅ ⊔ x₆` to `⊤` whereas the join diagonal below gives the
*correct* free value `x₅ ⊔ x₆ = x₈`.  These identities are proved from the
recursion, not read off a finite model. -/

/-- **Join diagonal.**  For `n` odd, `xₙ₊₂ ⊔ xₙ₊₃ = xₙ₊₅` — e.g.
`x₃ ⊔ x₄ = x₆`, `x₅ ⊔ x₆ = x₈`, `x₇ ⊔ x₈ = x₁₀`, … (the `fₖ` joins). -/
theorem nishimuraTerm_join_diagonal (g : H) {n : ℕ} (hn : n % 2 = 1) :
    nishimuraTerm g (n + 2) ⊔ nishimuraTerm g (n + 3) = nishimuraTerm g (n + 5) :=
  (by simp [nishimuraTerm, hn] : nishimuraTerm g (n + 5)
        = nishimuraTerm g (n + 2) ⊔ nishimuraTerm g (n + 3)).symm

/-- **Implication diagonal.**  For `n` even, `xₙ₊₃ ⇨ xₙ₊₂ = xₙ₊₅` — e.g.
`x₃ ⇨ x₂ = x₅`, `x₅ ⇨ x₄ = x₇`, `x₇ ⇨ x₆ = x₉`, … (the `gₖ` spine). -/
theorem nishimuraTerm_himp_diagonal (g : H) {n : ℕ} (hn : n % 2 = 0) :
    nishimuraTerm g (n + 3) ⇨ nishimuraTerm g (n + 2) = nishimuraTerm g (n + 5) :=
  (by simp [nishimuraTerm, hn] : nishimuraTerm g (n + 5)
        = nishimuraTerm g (n + 3) ⇨ nishimuraTerm g (n + 2)).symm

/-- The join diagonal lands inside the ladder (a first closure increment). -/
theorem isLadderValue_join_diagonal (g : H) {n : ℕ} (hn : n % 2 = 1) :
    IsLadderValue g (nishimuraTerm g (n + 2) ⊔ nishimuraTerm g (n + 3)) :=
  Or.inr ⟨n + 5, nishimuraTerm_join_diagonal g hn⟩

/-- The implication diagonal lands inside the ladder (a first closure
increment). -/
theorem isLadderValue_himp_diagonal (g : H) {n : ℕ} (hn : n % 2 = 0) :
    IsLadderValue g (nishimuraTerm g (n + 3) ⇨ nishimuraTerm g (n + 2)) :=
  Or.inr ⟨n + 5, nishimuraTerm_himp_diagonal g hn⟩

end NormalForm

end FalseWork.Lattice
