/-
Copyright (c) 2026 Chris Brink. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Brink

# The math anchor's substrate: truncations of the Rieger–Nishimura lattice
(math anchor, Phases 2–4; pre-registered in `validation/claims/math-anchor-cantor-floor.md`)

The free Heyting algebra on one generator `F(1)` is the Rieger–Nishimura
lattice (Rieger 1957; Nishimura 1960).  It is infinite, so the four-position
forced-kernel experiment cannot be run on it by `decide`.  The **canonical
finite truncations** are the finite one-generated Heyting algebras: by
Citkin's algebraic proof of the Nishimura theorem (*Logics* 2(4), 2024,
Theorems 6 & 8), **for every `n > 1` there is exactly one one-generated
Heyting algebra `Z_n` of cardinality `n`** (up to isomorphism), namely the
algebra defined by the relation `x_n = 1` in the Nishimura term sequence

```
x_0 = g ⊓ ¬g (= ⊥),  x_1 = ¬g,  x_2 = g,
x_{2n+3} = x_{2n+1} ⇨ x_{2n},   x_{2n+4} = x_{2n+1} ⊔ x_{2n+2}.
```

This *removes the truncation-arbitrariness risk pre-registered as the most
likely failure mode*: the truncation parameter is a single integer `n`, and
"stability across truncations" is a well-posed question.

## What this file proves (all by `decide`, all kernel-checked)

Each algebra below is certified as `Z_n` by two facts: it has cardinality `n`
(`Fintype.card`), and every element is an explicit Heyting term in the
generator `g` (`*_one_generated`).  By Citkin's uniqueness theorem **[C]**
that pins it as *the* `Z_n`.  Then the forced-kernel experiment runs:

* **`Z_5` (and below): no kernel works** (`Z5.no_kernel`).  Every element is
  regular or has `⊥` complement, so some cell is always empty.  The
  four-position partition needs cardinality ≥ 6 to be non-degenerate.

* **`Z_6` *is* the music lattice.**  `Div12` — the divisor lattice of 12, the
  music anchor's substrate — is itself a 6-element one-generated Heyting
  algebra, generated by the **tritone**: every element of `Div12` is a
  Nishimura term in `two` (`Div12.one_generated_by_tritone`).  By Citkin's
  uniqueness theorem [C], `Div12 ≅ Z_6`.  The music substrate was never
  music-specific: it is the cardinality-6 truncation of the free Heyting
  algebra on one generator, and the tritone is the free generator.

* **`Z_7`, `Z_8`: unique forced kernel = the generator** (`Z7.kernel_unique`,
  `Z8.kernel_unique`), with the same witnesses in Nishimura terms.

* **Stability (pre-registered outcome A).**  Bundled as
  `rn_truncation_outcome_A`: at every checked truncation (`n = 5, 6, 7, 8`)
  the kernel at which all four cells are inhabited is **unique and equal to
  the free generator** (vacuously none for `n = 5`), and the four cells are
  inhabited by the *same* four terms at every `n ≥ 6`:

  | Cell           | Term        | in `Div12 = Z_6`            |
  |----------------|-------------|------------------------------|
  | Infrastructure | `g`         | tritone `⟨6⟩`               |
  | Refusal        | `¬g`        | augmented triad `⟨4⟩`       |
  | Exploitation   | `¬¬g`       | diminished seventh `⟨3⟩`    |
  | Distribution   | `g ⊔ ¬g`    | whole-tone hexachord `⟨2⟩`  |

  The Exploitation witness is literally `¬¬g` — the double-negation
  non-collapse `¬¬g ≠ g` of intuitionistic logic (`*_g_non_regular`).

## Pre-registration audit (against `math-anchor-cantor-floor.md`)

Outcomes pre-registered: (A) unique stable kernel; (B) multiple kernels;
(C) no kernel anywhere; (D) truncation-dependent kernel.  **Result: (A)** on
the checked range `n ∈ {5,6,7,8}` (with the sharpening that `n = 5` is
degenerate — below cardinality 6 there is no kernel at all).  The extension
to *all* `n` is proved abstractly in `NishimuraKernelLaw.lean`
(`nishimura_kernel_unique`): conditional only on the classical Nishimura
enumeration **[C]**, the unique four-cell kernel of *every* one-generated
Heyting algebra with ordinary generator — every `Z_n` with `n ≥ 6`, and the
full Rieger–Nishimura lattice itself — is the free generator.

## Interpretation honesty

The cells get *logical* names from the lattice's own structure: `g`, `¬g`,
`¬¬g`, `g ⊔ ¬g`.  This is intuitionistic propositional logic on **one**
generator — chosen as the *simplest* free Heyting algebra, not forced by
"mathematics".  No provability/Gödel content is claimed: the Gödel resonance
of the math anchor lives in the Cantor/Lawvere floor (`MathFloorCantor.lean`),
not in this lattice.

## Sources

* Citkin, A. (2024). An Algebraic Proof of the Nishimura Theorem.
  *Logics* 2(4), 148–157.  (Theorem 6: uniqueness of `Z_n`; Theorem 8:
  `x_n = 1` defines `Z_n`; Corollary 9: the infinite one-generated Heyting
  algebra is free.)
* Nishimura, I. (1960). On formulas of one variable in intuitionistic
  propositional calculus. *J. Symb. Log.* 25, 327–331.
* Bumpus, B. M. & Kocsis, Z. A. Degree of satisfiability in Heyting
  algebras.  (Rieger–Nishimura term recursion.)
-/
import Mathlib.Order.Heyting.Basic
import Mathlib.Data.Fintype.Basic
import FalseWorkPapers.Lattice.FourPositionLattice
import FalseWorkPapers.Examples.DivisorLattice12

namespace FalseWork.Lattice

/-! ## Decidability for the Layer-L cell predicates

The four predicates of `FourPositionLattice` are `def`s, so `decide` cannot
see through them without explicit `Decidable` instances.  Provide them for
any Heyting algebra with decidable `≤` and `=`. -/

section DecInstances

variable {H : Type*} [HeytingAlgebra H]

instance (a x : H) [Decidable (x ≤ a)] :
    Decidable (IsLatticeInfrastructure a x) :=
  decidable_of_iff (x ≤ a) Iff.rfl

instance (a x : H) [Decidable (x ≤ aᶜ)] :
    Decidable (IsLatticeRefusal a x) :=
  decidable_of_iff (x ≤ aᶜ) Iff.rfl

instance (a x : H) [Decidable (x ≤ aᶜᶜ)] [Decidable (x ≤ a)] :
    Decidable (IsLatticeExploitation a x) :=
  decidable_of_iff (x ≤ aᶜᶜ ∧ ¬ x ≤ a) Iff.rfl

instance (a x : H) [DecidableEq H] :
    Decidable (IsLatticeDistribution a x) :=
  decidable_of_iff ((x ⊓ a ≠ ⊥) ∧ (x ⊓ aᶜ ≠ ⊥)) Iff.rfl

end DecInstances

/-- **All four Layer-L cells are simultaneously inhabited at kernel `a`.**
This is the non-degeneracy condition of the four-position partition: the
partition theorem (`lattice_four_position_partition`) always holds, but only
kernels satisfying this predicate make all four cells non-vacuous. -/
def AllFourCellsInhabited {H : Type*} [HeytingAlgebra H] (a : H) : Prop :=
  (∃ x, x ≠ ⊥ ∧ IsLatticeInfrastructure a x) ∧
  (∃ x, IsLatticeDistribution a x) ∧
  (∃ x, IsLatticeExploitation a x) ∧
  (∃ x, x ≠ ⊥ ∧ IsLatticeRefusal a x)

instance {H : Type*} [HeytingAlgebra H] [Fintype H] [DecidableEq H]
    [DecidableLE H] (a : H) : Decidable (AllFourCellsInhabited a) :=
  decidable_of_iff
    ((∃ x, x ≠ ⊥ ∧ x ≤ a) ∧
     (∃ x, (x ⊓ a ≠ ⊥) ∧ (x ⊓ aᶜ ≠ ⊥)) ∧
     (∃ x, x ≤ aᶜᶜ ∧ ¬ x ≤ a) ∧
     (∃ x, x ≠ ⊥ ∧ x ≤ aᶜ))
    Iff.rfl

namespace Examples

/-! ## `Z_5`: the largest truncation with NO four-cell kernel

`Z_5 = {⊥, g, ¬g, g ⊔ ¬g, ⊤}`: bottom, two atoms, their join, top.  The
generator `g` is *regular* (`¬¬g = g`), and the dense element `g ⊔ ¬g` has
`⊥` complement, so no element passes both non-degeneracy requirements. -/

inductive Z5 : Type
  | bot | g | ng | gng | top
  deriving DecidableEq, Repr

namespace Z5

instance : Fintype Z5 :=
  ⟨{bot, g, ng, gng, top}, by intro x; cases x <;> decide⟩

/-- Order: `⊥ < {g, ¬g} < g⊔¬g < ⊤`. -/
def leb : Z5 → Z5 → Bool
  | bot, _    => true
  | g,   g    => true
  | g,   gng  => true
  | g,   top  => true
  | ng,  ng   => true
  | ng,  gng  => true
  | ng,  top  => true
  | gng, gng  => true
  | gng, top  => true
  | top, top  => true
  | _,   _    => false

instance : LE Z5 := ⟨fun a b => leb a b = true⟩
instance : LT Z5 := ⟨fun a b => a ≤ b ∧ ¬ b ≤ a⟩

instance decLE : ∀ a b : Z5, Decidable (a ≤ b) := fun a b => by
  show Decidable (leb a b = true); exact decEq _ _

instance : DecidableLE Z5 := decLE

def meet : Z5 → Z5 → Z5
  | bot, _   => bot
  | _,   bot => bot
  | top, y   => y
  | x,   top => x
  | g,   g   => g
  | g,   ng  => bot
  | g,   gng => g
  | ng,  g   => bot
  | ng,  ng  => ng
  | ng,  gng => ng
  | gng, g   => g
  | gng, ng  => ng
  | gng, gng => gng

def join : Z5 → Z5 → Z5
  | bot, y   => y
  | x,   bot => x
  | top, _   => top
  | _,   top => top
  | g,   g   => g
  | g,   ng  => gng
  | g,   gng => gng
  | ng,  g   => gng
  | ng,  ng  => ng
  | ng,  gng => gng
  | gng, g   => gng
  | gng, ng  => gng
  | gng, gng => gng

instance : Min Z5 := ⟨meet⟩
instance : Max Z5 := ⟨join⟩
instance : Top Z5 := ⟨top⟩
instance : Bot Z5 := ⟨bot⟩

def himpFun : Z5 → Z5 → Z5
  | bot, _   => top
  | top, y   => y
  | g,   bot => ng
  | g,   g   => top
  | g,   ng  => ng
  | g,   gng => top
  | g,   top => top
  | ng,  bot => g
  | ng,  g   => g
  | ng,  ng  => top
  | ng,  gng => top
  | ng,  top => top
  | gng, bot => bot
  | gng, g   => g
  | gng, ng  => ng
  | gng, gng => top
  | gng, top => top

instance : HImp Z5 := ⟨himpFun⟩
instance : Compl Z5 := ⟨fun a => himpFun a bot⟩

instance : PartialOrder Z5 where
  le := (· ≤ ·)
  lt := (· < ·)
  le_refl       := fun a       => by cases a <;> decide
  le_trans      := fun a b c   => by cases a <;> cases b <;> cases c <;> decide
  le_antisymm   := fun a b     => by cases a <;> cases b <;> decide
  lt_iff_le_not_ge := fun _ _  => Iff.rfl

instance : SemilatticeInf Z5 where
  inf           := (· ⊓ ·)
  inf_le_left   := fun a b     => by cases a <;> cases b <;> decide
  inf_le_right  := fun a b     => by cases a <;> cases b <;> decide
  le_inf        := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : SemilatticeSup Z5 where
  sup           := (· ⊔ ·)
  le_sup_left   := fun a b     => by cases a <;> cases b <;> decide
  le_sup_right  := fun a b     => by cases a <;> cases b <;> decide
  sup_le        := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : Lattice Z5 where
  __ := (inferInstance : SemilatticeInf Z5)
  __ := (inferInstance : SemilatticeSup Z5)

instance : DistribLattice Z5 where
  le_sup_inf    := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : BoundedOrder Z5 where
  top := top
  bot := bot
  le_top a := by cases a <;> decide
  bot_le a := by cases a <;> decide

theorem le_himp_iff_z5 (a b c : Z5) : a ≤ b ⇨ c ↔ a ⊓ b ≤ c := by
  cases a <;> cases b <;> cases c <;> decide

instance heytingAlgebra : HeytingAlgebra Z5 :=
  HeytingAlgebra.ofHImp himpFun le_himp_iff_z5

/-- `Z_5` certification: the named elements are the Nishimura terms in `g`,
and the generator is **regular** (`¬¬g = g`) — which is exactly why no
four-cell kernel can exist here. -/
theorem rn_terms :
    (g : Z5)ᶜ = ng ∧ ((g : Z5)ᶜ)ᶜ = g ∧ (g : Z5) ⊔ gᶜ = gng ∧
    (g : Z5) ⊓ gᶜ = ⊥ := by decide

/-- `Z_5` is one-generated: every element is a Heyting term in `g`. -/
theorem one_generated :
    ∀ y : Z5, y = g ∨ y = gᶜ ∨ y = g ⊔ gᶜ ∨ y = g ⊓ gᶜ ∨ y = ⊤ := by decide

/-- **Negative result (kernel-checked).**  No element of `Z_5` makes all four
cells of the four-position partition simultaneously inhabited.  Below
cardinality 6 the partition is always degenerate.

Prior-art note: since the four-cell condition is equivalent to being an
*ordinary* element (`allFourCellsInhabited_iff`, `NishimuraKernelLaw.lean`),
this is a kernel-checked re-derivation of an observation already in
Citkin 2024 §2.1 ("the algebras `Z_i`, `i ∈ [2,5]`, do not contain any
ordinary elements") — known, not new. -/
theorem no_kernel : ∀ a : Z5, ¬ AllFourCellsInhabited a := by decide

end Z5

/-! ## `Z_7`: seven elements, unique kernel = the generator -/

inductive Z7 : Type
  | bot | g | ng | nng | gng | x6 | top
  deriving DecidableEq, Repr

namespace Z7

instance : Fintype Z7 :=
  ⟨{bot, g, ng, nng, gng, x6, top}, by intro x; cases x <;> decide⟩

/-- Order: `⊥`; atoms `g, ¬g`; `¬¬g` covers `g`; `g⊔¬g` covers `g, ¬g`;
`x_6 = ¬¬g ⊔ (g⊔¬g)` covers both; `⊤`. -/
def leb : Z7 → Z7 → Bool
  | bot, _    => true
  | g,   g    => true
  | g,   nng  => true
  | g,   gng  => true
  | g,   x6   => true
  | g,   top  => true
  | ng,  ng   => true
  | ng,  gng  => true
  | ng,  x6   => true
  | ng,  top  => true
  | nng, nng  => true
  | nng, x6   => true
  | nng, top  => true
  | gng, gng  => true
  | gng, x6   => true
  | gng, top  => true
  | x6,  x6   => true
  | x6,  top  => true
  | top, top  => true
  | _,   _    => false

instance : LE Z7 := ⟨fun a b => leb a b = true⟩
instance : LT Z7 := ⟨fun a b => a ≤ b ∧ ¬ b ≤ a⟩

instance decLE : ∀ a b : Z7, Decidable (a ≤ b) := fun a b => by
  show Decidable (leb a b = true); exact decEq _ _

instance : DecidableLE Z7 := decLE

def meet : Z7 → Z7 → Z7
  | bot, _   => bot
  | _,   bot => bot
  | top, y   => y
  | x,   top => x
  | g,   g   => g
  | g,   ng  => bot
  | g,   nng => g
  | g,   gng => g
  | g,   x6  => g
  | ng,  g   => bot
  | ng,  ng  => ng
  | ng,  nng => bot
  | ng,  gng => ng
  | ng,  x6  => ng
  | nng, g   => g
  | nng, ng  => bot
  | nng, nng => nng
  | nng, gng => g
  | nng, x6  => nng
  | gng, g   => g
  | gng, ng  => ng
  | gng, nng => g
  | gng, gng => gng
  | gng, x6  => gng
  | x6,  g   => g
  | x6,  ng  => ng
  | x6,  nng => nng
  | x6,  gng => gng
  | x6,  x6  => x6

def join : Z7 → Z7 → Z7
  | bot, y   => y
  | x,   bot => x
  | top, _   => top
  | _,   top => top
  | g,   g   => g
  | g,   ng  => gng
  | g,   nng => nng
  | g,   gng => gng
  | g,   x6  => x6
  | ng,  g   => gng
  | ng,  ng  => ng
  | ng,  nng => x6
  | ng,  gng => gng
  | ng,  x6  => x6
  | nng, g   => nng
  | nng, ng  => x6
  | nng, nng => nng
  | nng, gng => x6
  | nng, x6  => x6
  | gng, g   => gng
  | gng, ng  => gng
  | gng, nng => x6
  | gng, gng => gng
  | gng, x6  => x6
  | x6,  g   => x6
  | x6,  ng  => x6
  | x6,  nng => x6
  | x6,  gng => x6
  | x6,  x6  => x6

instance : Min Z7 := ⟨meet⟩
instance : Max Z7 := ⟨join⟩
instance : Top Z7 := ⟨top⟩
instance : Bot Z7 := ⟨bot⟩

def himpFun : Z7 → Z7 → Z7
  | bot, _   => top
  | top, y   => y
  | g,   bot => ng
  | g,   g   => top
  | g,   ng  => ng
  | g,   nng => top
  | g,   gng => top
  | g,   x6  => top
  | g,   top => top
  | ng,  bot => nng
  | ng,  g   => nng
  | ng,  ng  => top
  | ng,  nng => nng
  | ng,  gng => top
  | ng,  x6  => top
  | ng,  top => top
  | nng, bot => ng
  | nng, g   => gng
  | nng, ng  => ng
  | nng, nng => top
  | nng, gng => gng
  | nng, x6  => top
  | nng, top => top
  | gng, bot => bot
  | gng, g   => nng
  | gng, ng  => ng
  | gng, nng => nng
  | gng, gng => top
  | gng, x6  => top
  | gng, top => top
  | x6,  bot => bot
  | x6,  g   => g
  | x6,  ng  => ng
  | x6,  nng => nng
  | x6,  gng => gng
  | x6,  x6  => top
  | x6,  top => top

instance : HImp Z7 := ⟨himpFun⟩
instance : Compl Z7 := ⟨fun a => himpFun a bot⟩

instance : PartialOrder Z7 where
  le := (· ≤ ·)
  lt := (· < ·)
  le_refl       := fun a       => by cases a <;> decide
  le_trans      := fun a b c   => by cases a <;> cases b <;> cases c <;> decide
  le_antisymm   := fun a b     => by cases a <;> cases b <;> decide
  lt_iff_le_not_ge := fun _ _  => Iff.rfl

instance : SemilatticeInf Z7 where
  inf           := (· ⊓ ·)
  inf_le_left   := fun a b     => by cases a <;> cases b <;> decide
  inf_le_right  := fun a b     => by cases a <;> cases b <;> decide
  le_inf        := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : SemilatticeSup Z7 where
  sup           := (· ⊔ ·)
  le_sup_left   := fun a b     => by cases a <;> cases b <;> decide
  le_sup_right  := fun a b     => by cases a <;> cases b <;> decide
  sup_le        := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : Lattice Z7 where
  __ := (inferInstance : SemilatticeInf Z7)
  __ := (inferInstance : SemilatticeSup Z7)

instance : DistribLattice Z7 where
  le_sup_inf    := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : BoundedOrder Z7 where
  top := top
  bot := bot
  le_top a := by cases a <;> decide
  bot_le a := by cases a <;> decide

theorem le_himp_iff_z7 (a b c : Z7) : a ≤ b ⇨ c ↔ a ⊓ b ≤ c := by
  cases a <;> cases b <;> cases c <;> decide

instance heytingAlgebra : HeytingAlgebra Z7 :=
  HeytingAlgebra.ofHImp himpFun le_himp_iff_z7

/-- `Z_7` certification: the named elements are the Nishimura terms in `g`,
including the Prop-10 coincidence `x_5 = x_4` (`¬¬g ⇨ g = g ⊔ ¬g`) that is
characteristic of `n = 7`. -/
theorem rn_terms :
    (g : Z7)ᶜ = ng ∧ ((g : Z7)ᶜ)ᶜ = nng ∧ (g : Z7) ⊔ gᶜ = gng ∧
    (g : Z7) ⊓ gᶜ = ⊥ ∧ ((nng : Z7) ⇨ g) = gng ∧ (nng : Z7) ⊔ gng = x6 := by
  decide

/-- `Z_7` is one-generated: every element is a Heyting term in `g`. -/
theorem one_generated :
    ∀ y : Z7, y = g ∨ y = gᶜ ∨ y = gᶜᶜ ∨ y = g ⊔ gᶜ ∨ y = g ⊓ gᶜ ∨
      y = gᶜᶜ ⊔ (g ⊔ gᶜ) ∨ y = ⊤ := by decide

/-- The generator is non-regular: `¬¬g ≠ g` — the double-negation
non-collapse that makes Exploitation inhabitable. -/
theorem g_non_regular : ((g : Z7)ᶜ)ᶜ ≠ g := by decide

/-- The four cells at the generator kernel, inhabited by the four Nishimura
terms: `g` (Infrastructure), `¬g` (Refusal), `¬¬g` (Exploitation),
`g ⊔ ¬g` (Distribution). -/
theorem witness :
    IsLatticeInfrastructure (g : Z7) g ∧
    IsLatticeRefusal        (g : Z7) ng ∧
    IsLatticeExploitation   (g : Z7) nng ∧
    IsLatticeDistribution   (g : Z7) gng := by decide

/-- **Unique forced kernel.**  In `Z_7` the generator `g` is the *only*
element at which all four cells are inhabited. -/
theorem kernel_unique : ∀ a : Z7, AllFourCellsInhabited a ↔ a = g := by decide

end Z7

/-! ## `Z_8`: eight elements, unique kernel = the generator

First truncation where `x_5 = ¬¬g ⇨ g` is a *new* element (the ladder's next
rung), checking stability one step beyond the `Div12`-sized case. -/

inductive Z8 : Type
  | bot | g | ng | nng | gng | x5 | x6 | top
  deriving DecidableEq, Repr

namespace Z8

instance : Fintype Z8 :=
  ⟨{bot, g, ng, nng, gng, x5, x6, top}, by intro x; cases x <;> decide⟩

/-- Order: `⊥`; atoms `g, ¬g`; `¬¬g` covers `g`; `g⊔¬g` covers `g, ¬g`;
`x_5 = ¬¬g ⇨ g` covers `g⊔¬g`; `x_6 = ¬¬g ⊔ (g⊔¬g)` covers `¬¬g, g⊔¬g`;
`⊤` covers `x_5, x_6`. -/
def leb : Z8 → Z8 → Bool
  | bot, _    => true
  | g,   g    => true
  | g,   nng  => true
  | g,   gng  => true
  | g,   x5   => true
  | g,   x6   => true
  | g,   top  => true
  | ng,  ng   => true
  | ng,  gng  => true
  | ng,  x5   => true
  | ng,  x6   => true
  | ng,  top  => true
  | nng, nng  => true
  | nng, x6   => true
  | nng, top  => true
  | gng, gng  => true
  | gng, x5   => true
  | gng, x6   => true
  | gng, top  => true
  | x5,  x5   => true
  | x5,  top  => true
  | x6,  x6   => true
  | x6,  top  => true
  | top, top  => true
  | _,   _    => false

instance : LE Z8 := ⟨fun a b => leb a b = true⟩
instance : LT Z8 := ⟨fun a b => a ≤ b ∧ ¬ b ≤ a⟩

instance decLE : ∀ a b : Z8, Decidable (a ≤ b) := fun a b => by
  show Decidable (leb a b = true); exact decEq _ _

instance : DecidableLE Z8 := decLE

def meet : Z8 → Z8 → Z8
  | bot, _   => bot
  | _,   bot => bot
  | top, y   => y
  | x,   top => x
  | g,   g   => g
  | g,   ng  => bot
  | g,   nng => g
  | g,   gng => g
  | g,   x5  => g
  | g,   x6  => g
  | ng,  g   => bot
  | ng,  ng  => ng
  | ng,  nng => bot
  | ng,  gng => ng
  | ng,  x5  => ng
  | ng,  x6  => ng
  | nng, g   => g
  | nng, ng  => bot
  | nng, nng => nng
  | nng, gng => g
  | nng, x5  => g
  | nng, x6  => nng
  | gng, g   => g
  | gng, ng  => ng
  | gng, nng => g
  | gng, gng => gng
  | gng, x5  => gng
  | gng, x6  => gng
  | x5,  g   => g
  | x5,  ng  => ng
  | x5,  nng => g
  | x5,  gng => gng
  | x5,  x5  => x5
  | x5,  x6  => gng
  | x6,  g   => g
  | x6,  ng  => ng
  | x6,  nng => nng
  | x6,  gng => gng
  | x6,  x5  => gng
  | x6,  x6  => x6

def join : Z8 → Z8 → Z8
  | bot, y   => y
  | x,   bot => x
  | top, _   => top
  | _,   top => top
  | g,   g   => g
  | g,   ng  => gng
  | g,   nng => nng
  | g,   gng => gng
  | g,   x5  => x5
  | g,   x6  => x6
  | ng,  g   => gng
  | ng,  ng  => ng
  | ng,  nng => x6
  | ng,  gng => gng
  | ng,  x5  => x5
  | ng,  x6  => x6
  | nng, g   => nng
  | nng, ng  => x6
  | nng, nng => nng
  | nng, gng => x6
  | nng, x5  => top
  | nng, x6  => x6
  | gng, g   => gng
  | gng, ng  => gng
  | gng, nng => x6
  | gng, gng => gng
  | gng, x5  => x5
  | gng, x6  => x6
  | x5,  g   => x5
  | x5,  ng  => x5
  | x5,  nng => top
  | x5,  gng => x5
  | x5,  x5  => x5
  | x5,  x6  => top
  | x6,  g   => x6
  | x6,  ng  => x6
  | x6,  nng => x6
  | x6,  gng => x6
  | x6,  x5  => top
  | x6,  x6  => x6

instance : Min Z8 := ⟨meet⟩
instance : Max Z8 := ⟨join⟩
instance : Top Z8 := ⟨top⟩
instance : Bot Z8 := ⟨bot⟩

def himpFun : Z8 → Z8 → Z8
  | bot, _   => top
  | top, y   => y
  | g,   bot => ng
  | g,   g   => top
  | g,   ng  => ng
  | g,   nng => top
  | g,   gng => top
  | g,   x5  => top
  | g,   x6  => top
  | g,   top => top
  | ng,  bot => nng
  | ng,  g   => nng
  | ng,  ng  => top
  | ng,  nng => nng
  | ng,  gng => top
  | ng,  x5  => top
  | ng,  x6  => top
  | ng,  top => top
  | nng, bot => ng
  | nng, g   => x5
  | nng, ng  => ng
  | nng, nng => top
  | nng, gng => x5
  | nng, x5  => x5
  | nng, x6  => top
  | nng, top => top
  | gng, bot => bot
  | gng, g   => nng
  | gng, ng  => ng
  | gng, nng => nng
  | gng, gng => top
  | gng, x5  => top
  | gng, x6  => top
  | gng, top => top
  | x5,  bot => bot
  | x5,  g   => nng
  | x5,  ng  => ng
  | x5,  nng => nng
  | x5,  gng => x6
  | x5,  x5  => top
  | x5,  x6  => x6
  | x5,  top => top
  | x6,  bot => bot
  | x6,  g   => g
  | x6,  ng  => ng
  | x6,  nng => nng
  | x6,  gng => x5
  | x6,  x5  => x5
  | x6,  x6  => top
  | x6,  top => top

instance : HImp Z8 := ⟨himpFun⟩
instance : Compl Z8 := ⟨fun a => himpFun a bot⟩

instance : PartialOrder Z8 where
  le := (· ≤ ·)
  lt := (· < ·)
  le_refl       := fun a       => by cases a <;> decide
  le_trans      := fun a b c   => by cases a <;> cases b <;> cases c <;> decide
  le_antisymm   := fun a b     => by cases a <;> cases b <;> decide
  lt_iff_le_not_ge := fun _ _  => Iff.rfl

instance : SemilatticeInf Z8 where
  inf           := (· ⊓ ·)
  inf_le_left   := fun a b     => by cases a <;> cases b <;> decide
  inf_le_right  := fun a b     => by cases a <;> cases b <;> decide
  le_inf        := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : SemilatticeSup Z8 where
  sup           := (· ⊔ ·)
  le_sup_left   := fun a b     => by cases a <;> cases b <;> decide
  le_sup_right  := fun a b     => by cases a <;> cases b <;> decide
  sup_le        := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : Lattice Z8 where
  __ := (inferInstance : SemilatticeInf Z8)
  __ := (inferInstance : SemilatticeSup Z8)

instance : DistribLattice Z8 where
  le_sup_inf    := fun a b c   => by cases a <;> cases b <;> cases c <;> decide

instance : BoundedOrder Z8 where
  top := top
  bot := bot
  le_top a := by cases a <;> decide
  bot_le a := by cases a <;> decide

theorem le_himp_iff_z8 (a b c : Z8) : a ≤ b ⇨ c ↔ a ⊓ b ≤ c := by
  cases a <;> cases b <;> cases c <;> decide

instance heytingAlgebra : HeytingAlgebra Z8 :=
  HeytingAlgebra.ofHImp himpFun le_himp_iff_z8

/-- `Z_8` certification: the named elements are the Nishimura terms in `g`.
Here `x_5 = ¬¬g ⇨ g` is a genuinely new rung (unlike at `n = 6, 7`), and the
Prop-10 coincidence moves up: `x_7 = x_5 ⇨ (g ⊔ ¬g) = x_6`. -/
theorem rn_terms :
    (g : Z8)ᶜ = ng ∧ ((g : Z8)ᶜ)ᶜ = nng ∧ (g : Z8) ⊔ gᶜ = gng ∧
    (g : Z8) ⊓ gᶜ = ⊥ ∧ ((nng : Z8) ⇨ g) = x5 ∧ (nng : Z8) ⊔ gng = x6 ∧
    ((x5 : Z8) ⇨ gng) = x6 ∧ (x5 : Z8) ⊔ x6 = ⊤ := by decide

/-- `Z_8` is one-generated: every element is a Heyting term in `g`. -/
theorem one_generated :
    ∀ y : Z8, y = g ∨ y = gᶜ ∨ y = gᶜᶜ ∨ y = g ⊔ gᶜ ∨ y = g ⊓ gᶜ ∨
      y = gᶜᶜ ⇨ g ∨ y = gᶜᶜ ⊔ (g ⊔ gᶜ) ∨ y = ⊤ := by decide

/-- The generator is non-regular: `¬¬g ≠ g`. -/
theorem g_non_regular : ((g : Z8)ᶜ)ᶜ ≠ g := by decide

/-- The four cells at the generator kernel, inhabited by the same four
Nishimura terms as at every other truncation. -/
theorem witness :
    IsLatticeInfrastructure (g : Z8) g ∧
    IsLatticeRefusal        (g : Z8) ng ∧
    IsLatticeExploitation   (g : Z8) nng ∧
    IsLatticeDistribution   (g : Z8) gng := by decide

/-- **Unique forced kernel.**  In `Z_8` the generator `g` is the *only*
element at which all four cells are inhabited. -/
theorem kernel_unique : ∀ a : Z8, AllFourCellsInhabited a ↔ a = g := by decide

end Z8

/-! ## `Div12` *is* `Z_6`: the music lattice is the 6-element truncation

The music anchor's substrate `Div12` (divisor lattice of 12 = subgroup
lattice of `ℤ/12`) is itself one-generated — by the **tritone** — with the
same Nishimura term structure.  By Citkin's uniqueness theorem **[C]**,
`Div12 ≅ Z_6`, the unique 6-element one-generated Heyting algebra.  The
music substrate is the cardinality-6 truncation of the free Heyting algebra
on one generator; the tritone is the free generator; and the music witness
cells are the Nishimura terms:

| Term      | `Div12`  | pitch-class object          |
|-----------|----------|------------------------------|
| `g ⊓ ¬g`  | `one`    | trivial `{0}`                |
| `¬g`      | `three`  | augmented triad `⟨4⟩`       |
| `g`       | `two`    | tritone `⟨6⟩`               |
| `¬¬g`     | `four`   | diminished seventh `⟨3⟩`    |
| `g ⊔ ¬g`  | `six`    | whole-tone hexachord `⟨2⟩`  |
| `x_6`     | `twelve` | full chromatic `ℤ/12`       |
-/

namespace Div12

/-- **`Div12` is one-generated by the tritone**: every element of the music
lattice is an explicit Heyting term in `two = ⟨6⟩`.  With
`Fintype.card Div12 = 6` and Citkin's uniqueness theorem [C], this
identifies the music lattice as `Z_6` — the cardinality-6 truncation of the
free Heyting algebra on one generator. -/
theorem one_generated_by_tritone :
    ∀ y : Div12, y = two ∨ y = twoᶜ ∨ y = twoᶜᶜ ∨ y = two ⊔ twoᶜ ∨
      y = two ⊓ twoᶜ ∨ y = twoᶜᶜ ⊔ (two ⊔ twoᶜ) := by decide

/-- The Nishimura terms in the tritone generator land on the named
pitch-class objects, including the Prop-10 coincidence
`x_5 = ¬¬g ⇨ g = g ⊔ ¬g` characteristic of `n = 6`. -/
theorem rn_terms :
    (two : Div12)ᶜ = three ∧ ((two : Div12)ᶜ)ᶜ = four ∧
    (two : Div12) ⊔ twoᶜ = six ∧ (two : Div12) ⊓ twoᶜ = one ∧
    ((four : Div12) ⇨ two) = six ∧ (four : Div12) ⊔ six = twelve := by decide

/-- **Unique forced kernel, upgraded to [K].**  The tritone is the *only*
element of `Div12` at which all four cells are inhabited.  (Previously
verified computationally in Wolfram — tag [C]; this is the kernel-checked
version.) -/
theorem kernel_unique : ∀ a : Div12, AllFourCellsInhabited a ↔ a = two := by
  decide

end Div12

/-! ## The stability bundle: pre-registered outcome (A) -/

/-- **Forced-kernel stability across the Rieger–Nishimura truncations
(pre-registered outcome A).**  Across the canonical finite truncations
`Z_n` of the free Heyting algebra on one generator:

* `n = 5`: no four-cell kernel exists (the partition needs cardinality ≥ 6);
* `n = 6` (= `Div12`, the music lattice): unique kernel = the generator
  (= the tritone);
* `n = 7`: unique kernel = the generator;
* `n = 8`: unique kernel = the generator.

The forced kernel is **unique and truncation-stable**: it is the free
generator at every checked truncation, with the four cells inhabited by the
same Nishimura terms `g, ¬g, ¬¬g, g ⊔ ¬g`.  The extension to all `n ≥ 6`
(and to the infinite Rieger–Nishimura lattice) is the all-n kernel law,
`nishimura_kernel_unique` in `NishimuraKernelLaw.lean`. -/
theorem rn_truncation_outcome_A :
    (∀ a : Z5, ¬ AllFourCellsInhabited a) ∧
    (∀ a : Div12, AllFourCellsInhabited a ↔ a = Div12.two) ∧
    (∀ a : Z7, AllFourCellsInhabited a ↔ a = Z7.g) ∧
    (∀ a : Z8, AllFourCellsInhabited a ↔ a = Z8.g) :=
  ⟨Z5.no_kernel, Div12.kernel_unique, Z7.kernel_unique, Z8.kernel_unique⟩

end Examples

end FalseWork.Lattice
