/-
Copyright (c) 2026 Chris Brink. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Brink

# The Nishimura normal form — Phase 1 (term closure)

This file is the active spine target registered at
`validation/claims/nishimura-normal-form.md`.  The goal of the full
development is to prove that the subalgebra generated by a single element
`g` of a Heyting algebra is exactly the **Rieger–Nishimura ladder** — the
set `{⊤} ∪ {nishimuraTerm g n : n}` of `NishimuraKernelLaw.lean`.  Proving
this discharges the one classical citation **[C]** still standing under the
all-`n` kernel law (`nishimura_kernel_unique`): the Nishimura enumeration
`hgen` becomes a Lean theorem rather than a quoted result, and the music
lattice's order-embedding (`div12OrderEmbedding`) upgrades to a *subalgebra*
embedding (Citkin's Prop. 3.1 in full).

**Phase 1 (this file, in progress).**  Closure of the ladder set under the
Heyting operations — the Rieger–Nishimura "tables" as derived identities.
This is the foundation for the structural induction that gives the normal
form.  Landed so far, all `sorry`-free:

* `IsLadderValue` and the basic memberships (`⊤`, `⊥`, the generator);
* the **complement table** `isLadderValue_compl`: `xₙᶜ` is again a ladder
  value (`⊤, x₃, x₁, x₁, ⊥` for `n = 0, 1, 2, 3, ≥ 4`);
* the **definitional diagonals** `nishimuraTerm_join_diagonal` /
  `nishimuraTerm_himp_diagonal`: the main diagonals of the join and
  implication tables, read straight off the term recursion (`xₙ₊₂ ⊔ xₙ₊₃ =
  xₙ₊₅` for `n` odd; `xₙ₊₃ ⇨ xₙ₊₂ = xₙ₊₅` for `n` even), with their closure
  corollaries.

Still open in Phase 1: the **off-diagonal** meet, join, and implication
entries (the genuine weeks-long core, by strong induction on the term
recursion). The certified-safe meet table on `x₀…x₆`, the literature Hasse
structure, and the collapse-artifact protocol are recorded in
`validation/claims/nishimura-normal-form.md`. Then Phases 2–4
(finite-truncation normal form, the abstract normal form discharging `hgen`,
and the `Div12` subalgebra upgrade).
-/
import Mathlib.Order.Heyting.Basic
import FalseWorkPapers.Examples.NishimuraKernelLaw

namespace FalseWork.Lattice

section NormalForm

variable {H : Type*} [HeytingAlgebra H]

/-- The **Rieger–Nishimura ladder values** in a generator `g`: `⊤` together
with the canonical term sequence `nishimuraTerm g n`.  The normal-form
theorem under construction is that this set is exactly the subalgebra
generated by `g`. -/
def IsLadderValue (g x : H) : Prop := x = ⊤ ∨ ∃ n : ℕ, x = nishimuraTerm g n

theorem isLadderValue_top (g : H) : IsLadderValue g ⊤ := Or.inl rfl

theorem isLadderValue_bot (g : H) : IsLadderValue g ⊥ :=
  Or.inr ⟨0, by simp [nishimuraTerm]⟩

theorem isLadderValue_gen (g : H) : IsLadderValue g g :=
  Or.inr ⟨2, by simp [nishimuraTerm]⟩

theorem isLadderValue_term (g : H) (n : ℕ) : IsLadderValue g (nishimuraTerm g n) :=
  Or.inr ⟨n, rfl⟩

/-! ### The complement table

In the Rieger–Nishimura ladder the complement of every term is again a
term: `x₀ᶜ = ⊤`, `x₁ᶜ = x₃` (`¬¬g`), `x₂ᶜ = x₁` (`¬g`), `x₃ᶜ = x₁`
(triple negation), and `xₙᶜ = ⊥ = x₀` for all `n ≥ 4`, because every such
term lies above `x₄ = ¬g ⊔ g`, whose complement is `⊥`. -/

/-- Every ladder term from index `4` on has complement `⊥`: it lies above
`x₄ = ¬g ⊔ g`, and `(¬g ⊔ g)ᶜ = ¬¬g ⊓ ¬g = ⊥`. -/
theorem compl_nishimuraTerm_ge_four (g : H) {n : ℕ} (hn : 4 ≤ n) :
    (nishimuraTerm g n)ᶜ = ⊥ := by
  have h4 : gᶜ ⊔ g ≤ nishimuraTerm g n := four_le_nishimuraTerm g n hn
  have hle : (nishimuraTerm g n)ᶜ ≤ (gᶜ ⊔ g)ᶜ := compl_anti h4
  rw [compl_sup] at hle
  have hz : gᶜᶜ ⊓ gᶜ = ⊥ := by rw [inf_comm]; exact inf_compl_self gᶜ
  rw [hz] at hle
  exact le_bot_iff.mp hle

/-- **Complement closure (the RN complement table).**  The complement of a
ladder term is again a ladder value. -/
theorem isLadderValue_compl (g : H) (n : ℕ) :
    IsLadderValue g (nishimuraTerm g n)ᶜ := by
  match n with
  | 0 => exact Or.inl (by simp [nishimuraTerm])
  | 1 => exact Or.inr ⟨3, by simp [nishimuraTerm]⟩
  | 2 => exact Or.inr ⟨1, by simp [nishimuraTerm]⟩
  | 3 => exact Or.inr ⟨1, by simp [nishimuraTerm]⟩
  | (k + 4) =>
      exact Or.inr ⟨0, by
        rw [compl_nishimuraTerm_ge_four g (by omega : 4 ≤ k + 4)]
        simp [nishimuraTerm]⟩

/-- Complement closure stated for the whole ladder set, `⊤` included
(`⊤ᶜ = ⊥`). -/
theorem isLadderValue_compl_of (g : H) {x : H} (hx : IsLadderValue g x) :
    IsLadderValue g xᶜ := by
  rcases hx with rfl | ⟨n, rfl⟩
  · exact Or.inr ⟨0, by simp [nishimuraTerm]⟩
  · exact isLadderValue_compl g n

/-! ### The definitional diagonals

The term recursion itself supplies the *main diagonals* of the join and
implication tables, with no order reasoning: for `n` odd the join of two
consecutive terms is the next term, and for `n` even the implication of two
consecutive terms is the next term.  These anchor the induction for the full
binary tables (the off-diagonal entries are the genuine work); see the
literature reference in `validation/claims/nishimura-normal-form.md`.

A caution recorded there: the finite truncations `Zₙ` collapse higher rungs, so
e.g. `Z₈` evaluates `x₅ ⊔ x₆` to `⊤` whereas the join diagonal below gives the
*correct* free value `x₅ ⊔ x₆ = x₈`.  These identities are proved from the
recursion, not read off a finite model. -/

/-- **Join diagonal.**  For `n` odd, `xₙ₊₂ ⊔ xₙ₊₃ = xₙ₊₅` — e.g.
`x₃ ⊔ x₄ = x₆`, `x₅ ⊔ x₆ = x₈`, `x₇ ⊔ x₈ = x₁₀`, … (the `fₖ` joins). -/
theorem nishimuraTerm_join_diagonal (g : H) {n : ℕ} (hn : n % 2 = 1) :
    nishimuraTerm g (n + 2) ⊔ nishimuraTerm g (n + 3) = nishimuraTerm g (n + 5) :=
  (by simp [nishimuraTerm, hn] : nishimuraTerm g (n + 5)
        = nishimuraTerm g (n + 2) ⊔ nishimuraTerm g (n + 3)).symm

/-- **Implication diagonal.**  For `n` even, `xₙ₊₃ ⇨ xₙ₊₂ = xₙ₊₅` — e.g.
`x₃ ⇨ x₂ = x₅`, `x₅ ⇨ x₄ = x₇`, `x₇ ⇨ x₆ = x₉`, … (the `gₖ` spine). -/
theorem nishimuraTerm_himp_diagonal (g : H) {n : ℕ} (hn : n % 2 = 0) :
    nishimuraTerm g (n + 3) ⇨ nishimuraTerm g (n + 2) = nishimuraTerm g (n + 5) :=
  (by simp [nishimuraTerm, hn] : nishimuraTerm g (n + 5)
        = nishimuraTerm g (n + 3) ⇨ nishimuraTerm g (n + 2)).symm

/-- The join diagonal lands inside the ladder (a first closure increment). -/
theorem isLadderValue_join_diagonal (g : H) {n : ℕ} (hn : n % 2 = 1) :
    IsLadderValue g (nishimuraTerm g (n + 2) ⊔ nishimuraTerm g (n + 3)) :=
  Or.inr ⟨n + 5, nishimuraTerm_join_diagonal g hn⟩

/-- The implication diagonal lands inside the ladder (a first closure
increment). -/
theorem isLadderValue_himp_diagonal (g : H) {n : ℕ} (hn : n % 2 = 0) :
    IsLadderValue g (nishimuraTerm g (n + 3) ⇨ nishimuraTerm g (n + 2)) :=
  Or.inr ⟨n + 5, nishimuraTerm_himp_diagonal g hn⟩

/-! ### The positive order generators

The Rieger–Nishimura order is characterised (see
`validation/claims/nishimura-normal-form.md`) by
`xₐ ≤ x_b ⟺ (a even ∧ b ≥ a) ∨ (a odd ∧ (b = a ∨ b ≥ a+3))`.  The full table
needs only the **positive** direction of this relation (the genuine
incomparabilities are never required for closure), and the positive direction
rests on two even-index generators proved here:

* `nishimuraTerm_even_le_add_two` — the `f`-chain ascends: `x_{2k} ≤ x_{2k+2}`;
* `nishimuraTerm_even_le_succ` — the keystone `x_{2k} ≤ x_{2k+1}`, which reduces
  via the recursion unfolds to the previous generator plus the Heyting
  modus-ponens `(a ⇨ b) ⊓ a ≤ b`, all at strictly lower index (no forward
  reference; the dependency graph is well-founded).
-/

/-- **`even ≤ +2`** (`f`-chain monotone): for even `n`, `xₙ ≤ xₙ₊₂`. -/
theorem nishimuraTerm_even_le_add_two (g : H) {n : ℕ} (hn : n % 2 = 0) :
    nishimuraTerm g n ≤ nishimuraTerm g (n + 2) := by
  obtain ⟨k, rfl⟩ : ∃ k, n = 2 * k := ⟨n / 2, by omega⟩
  match k with
  | 0 => simp only [nishimuraTerm]; exact bot_le
  | 1 =>
      show nishimuraTerm g 2 ≤ nishimuraTerm g 4
      simp only [nishimuraTerm]; exact le_sup_right
  | (j + 2) =>
      show nishimuraTerm g (2 * j + 4) ≤ nishimuraTerm g (2 * j + 6)
      have h6 : nishimuraTerm g (2 * j + 3) ⊔ nishimuraTerm g (2 * j + 4)
          = nishimuraTerm g (2 * j + 6) :=
        nishimuraTerm_join_diagonal g (n := 2 * j + 1) (by omega)
      rw [← h6]; exact le_sup_right

/-- **`even ≤ +1`** (the keystone generator): for even `n`, `xₙ ≤ xₙ₊₁`.  The
case `n ≥ 6` unfolds `xₙ₊₁ = xₙ₋₁ ⇨ xₙ₋₂` and `xₙ = xₙ₋₃ ⊔ xₙ₋₂` by the
recursion, reduces by `le_himp_iff` and distributivity to the modus-ponens
`xₙ₋₃ ⊓ (xₙ₋₃ ⇨ xₙ₋₄) ≤ xₙ₋₄`, and closes with `even ≤ +2` at a strictly
lower index. -/
theorem nishimuraTerm_even_le_succ (g : H) {n : ℕ} (hn : n % 2 = 0) :
    nishimuraTerm g n ≤ nishimuraTerm g (n + 1) := by
  obtain ⟨k, rfl⟩ : ∃ k, n = 2 * k := ⟨n / 2, by omega⟩
  match k with
  | 0 => simp only [nishimuraTerm]; exact bot_le
  | 1 => simp only [nishimuraTerm]; exact le_compl_compl
  | 2 =>
      show nishimuraTerm g 4 ≤ nishimuraTerm g 5
      have h5 : nishimuraTerm g 3 ⇨ nishimuraTerm g 2 = nishimuraTerm g 5 :=
        nishimuraTerm_himp_diagonal g (n := 0) (by omega)
      rw [← h5, le_himp_iff]
      simp only [nishimuraTerm]
      rw [inf_sup_right]
      refine sup_le ?_ inf_le_left
      rw [inf_compl_self]; exact bot_le
  | (j + 3) =>
      show nishimuraTerm g (2 * j + 6) ≤ nishimuraTerm g (2 * j + 7)
      have h7 : nishimuraTerm g (2 * j + 5) ⇨ nishimuraTerm g (2 * j + 4)
          = nishimuraTerm g (2 * j + 7) :=
        nishimuraTerm_himp_diagonal g (n := 2 * j + 2) (by omega)
      have h6 : nishimuraTerm g (2 * j + 3) ⊔ nishimuraTerm g (2 * j + 4)
          = nishimuraTerm g (2 * j + 6) :=
        nishimuraTerm_join_diagonal g (n := 2 * j + 1) (by omega)
      have h5 : nishimuraTerm g (2 * j + 3) ⇨ nishimuraTerm g (2 * j + 2)
          = nishimuraTerm g (2 * j + 5) :=
        nishimuraTerm_himp_diagonal g (n := 2 * j) (by omega)
      have hev : nishimuraTerm g (2 * j + 2) ≤ nishimuraTerm g (2 * j + 4) :=
        nishimuraTerm_even_le_add_two g (n := 2 * j + 2) (by omega)
      rw [← h7, le_himp_iff, ← h6, inf_sup_right]
      refine sup_le ?_ inf_le_left
      rw [← h5]
      refine le_trans ?_ hev
      rw [inf_comm]; exact himp_inf_le

/-- **`odd ≤ +3`**: for odd `n`, `xₙ ≤ xₙ₊₃` (the odd rung re-enters the order
three steps up).  `x₁ ≤ x₄` is `¬g ≤ ¬g ⊔ g`; the rest is the join diagonal. -/
theorem nishimuraTerm_odd_le_add_three (g : H) {n : ℕ} (hn : n % 2 = 1) :
    nishimuraTerm g n ≤ nishimuraTerm g (n + 3) := by
  obtain ⟨k, rfl⟩ : ∃ k, n = 2 * k + 1 := ⟨n / 2, by omega⟩
  match k with
  | 0 =>
      show nishimuraTerm g 1 ≤ nishimuraTerm g 4
      simp only [nishimuraTerm]; exact le_sup_left
  | (j + 1) =>
      show nishimuraTerm g (2 * j + 3) ≤ nishimuraTerm g (2 * j + 6)
      have h6 : nishimuraTerm g (2 * j + 3) ⊔ nishimuraTerm g (2 * j + 4)
          = nishimuraTerm g (2 * j + 6) :=
        nishimuraTerm_join_diagonal g (n := 2 * j + 1) (by omega)
      rw [← h6]; exact le_sup_left

/-- The even monotonicity, assembled: for even `a`, `xₐ ≤ x_{a+d}` for every
`d`.  Strong induction stepping by two (`even ≤ +2`) with the keystone `+1`
generator covering the odd offset; no incomparability is used. -/
theorem nishimuraTerm_even_le_add (g : H) :
    ∀ d a, a % 2 = 0 → nishimuraTerm g a ≤ nishimuraTerm g (a + d) := by
  intro d
  induction d using Nat.strong_induction_on with
  | _ d ih =>
    intro a ha
    match d with
    | 0 => simp
    | 1 => exact nishimuraTerm_even_le_succ g ha
    | (e + 2) =>
        have h2 : nishimuraTerm g a ≤ nishimuraTerm g (a + 2) :=
          nishimuraTerm_even_le_add_two g ha
        have hrec : nishimuraTerm g (a + 2) ≤ nishimuraTerm g (a + 2 + e) :=
          ih e (by omega) (a + 2) (by omega)
        have he : a + 2 + e = a + (e + 2) := by omega
        rw [he] at hrec
        exact le_trans h2 hrec

/-- The odd monotonicity, assembled: for odd `a` and `a + 3 ≤ b`, `xₐ ≤ x_b`
(via `odd ≤ +3` into the even chain). -/
theorem nishimuraTerm_odd_le (g : H) {a : ℕ} (ha : a % 2 = 1) {b : ℕ}
    (hb : a + 3 ≤ b) : nishimuraTerm g a ≤ nishimuraTerm g b := by
  obtain ⟨d, rfl⟩ : ∃ d, b = (a + 3) + d := ⟨b - (a + 3), by omega⟩
  exact le_trans (nishimuraTerm_odd_le_add_three g ha)
    (nishimuraTerm_even_le_add g d (a + 3) (by omega))

/-- **The positive Rieger–Nishimura order characterisation.**  Whenever the
parity/offset condition `(a even ∧ a ≤ b) ∨ (a odd ∧ (b = a ∨ a + 3 ≤ b))`
holds, `xₐ ≤ x_b`.  This is exactly the comparabilities the meet/join tables
need — and, by the dependency-graph exercise, all they need (the converse
incomparabilities never enter closure). -/
theorem nishimuraTerm_le_of (g : H) {a b : ℕ}
    (h : (a % 2 = 0 ∧ a ≤ b) ∨ (a % 2 = 1 ∧ (b = a ∨ a + 3 ≤ b))) :
    nishimuraTerm g a ≤ nishimuraTerm g b := by
  rcases h with ⟨ha, hab⟩ | ⟨ha, hb⟩
  · obtain ⟨d, rfl⟩ : ∃ d, b = a + d := ⟨b - a, by omega⟩
    exact nishimuraTerm_even_le_add g d a ha
  · rcases hb with rfl | hb
    · exact le_refl _
    · exact nishimuraTerm_odd_le g ha hb

/-! ### The join table and closure under `⊔`

By the dependency-graph exercise, `xₘ ⊔ xₙ` is `lub`, so it is `x_{max}` whenever
the two are comparable, and otherwise one of two incomparable diagonals — and the
incomparable pairs `m < n` are exactly `m` odd with `n ∈ {m+1, m+2}`. -/

/-- **Adjacent join** (`m` odd): `xₘ ⊔ xₘ₊₁ = xₘ₊₃`. -/
theorem nishimuraTerm_join_adjacent (g : H) {m : ℕ} (hm : m % 2 = 1) :
    nishimuraTerm g m ⊔ nishimuraTerm g (m + 1) = nishimuraTerm g (m + 3) := by
  obtain ⟨k, rfl⟩ : ∃ k, m = 2 * k + 1 := ⟨m / 2, by omega⟩
  match k with
  | 0 =>
      show nishimuraTerm g 1 ⊔ nishimuraTerm g 2 = nishimuraTerm g 4
      simp only [nishimuraTerm]
  | (j + 1) =>
      show nishimuraTerm g (2 * j + 3) ⊔ nishimuraTerm g (2 * j + 4)
          = nishimuraTerm g (2 * j + 6)
      exact nishimuraTerm_join_diagonal g (n := 2 * j + 1) (by omega)

/-- **Skip join** (`m` odd): `xₘ ⊔ xₘ₊₂ = xₘ₊₅`.  The `≥` half rewrites
`xₘ₊₅ = xₘ₊₂ ⊔ xₘ₊₃` (join diagonal) and `xₘ₊₃ = xₘ ⊔ xₘ₊₁` (adjacent join),
then reduces `xₘ₊₁ ≤ xₘ ⊔ xₘ₊₂` to `xₘ₊₁ ≤ xₘ₊₂` (`even ≤ +1`). -/
theorem nishimuraTerm_join_skip (g : H) {m : ℕ} (hm : m % 2 = 1) :
    nishimuraTerm g m ⊔ nishimuraTerm g (m + 2) = nishimuraTerm g (m + 5) := by
  have hd : nishimuraTerm g (m + 2) ⊔ nishimuraTerm g (m + 3)
      = nishimuraTerm g (m + 5) := nishimuraTerm_join_diagonal g (n := m) hm
  apply le_antisymm
  · apply sup_le
    · exact nishimuraTerm_le_of g (Or.inr ⟨hm, Or.inr (by omega)⟩)
    · exact nishimuraTerm_le_of g (Or.inr ⟨by omega, Or.inr (by omega)⟩)
  · rw [← hd]
    apply sup_le
    · exact le_sup_right
    · rw [← nishimuraTerm_join_adjacent g hm]
      exact sup_le le_sup_left
        (le_trans (nishimuraTerm_even_le_succ g (by omega)) le_sup_right)

/-- The join of two ladder terms with `m ≤ n` is a ladder value: `x_n` when
comparable, else the adjacent or skip diagonal. -/
theorem isLadderValue_join_le (g : H) {m n : ℕ} (hmn : m ≤ n) :
    IsLadderValue g (nishimuraTerm g m ⊔ nishimuraTerm g n) := by
  by_cases hcomp : (m % 2 = 0) ∨ (m = n) ∨ (m + 3 ≤ n)
  · have hle : nishimuraTerm g m ≤ nishimuraTerm g n := by
      rcases hcomp with he | rfl | h3
      · exact nishimuraTerm_le_of g (Or.inl ⟨he, hmn⟩)
      · exact le_refl _
      · rcases Nat.mod_two_eq_zero_or_one m with he | ho
        · exact nishimuraTerm_le_of g (Or.inl ⟨he, hmn⟩)
        · exact nishimuraTerm_le_of g (Or.inr ⟨ho, Or.inr h3⟩)
    rw [sup_eq_right.mpr hle]
    exact isLadderValue_term g n
  · have hmodd : m % 2 = 1 := by omega
    have hcase : n = m + 1 ∨ n = m + 2 := by omega
    rcases hcase with rfl | rfl
    · rw [nishimuraTerm_join_adjacent g hmodd]; exact isLadderValue_term g (m + 3)
    · rw [nishimuraTerm_join_skip g hmodd]; exact isLadderValue_term g (m + 5)

/-- **Join closure (the RN join table).**  The join of two ladder terms is a
ladder value. -/
theorem isLadderValue_join (g : H) (m n : ℕ) :
    IsLadderValue g (nishimuraTerm g m ⊔ nishimuraTerm g n) := by
  rcases le_total m n with hmn | hmn
  · exact isLadderValue_join_le g hmn
  · rw [sup_comm]; exact isLadderValue_join_le g hmn

/-- **Join closure for the whole ladder set**, `⊤` included. -/
theorem isLadderValue_sup (g : H) {x y : H} (hx : IsLadderValue g x)
    (hy : IsLadderValue g y) : IsLadderValue g (x ⊔ y) := by
  rcases hx with rfl | ⟨m, rfl⟩
  · rw [top_sup_eq]; exact isLadderValue_top g
  · rcases hy with rfl | ⟨n, rfl⟩
    · rw [sup_top_eq]; exact isLadderValue_top g
    · exact isLadderValue_join g m n

/-! ### The meet table and closure under `⊓`

Dual to join: `xₘ ⊓ xₙ` is `glb`, so `x_{min}` when comparable, else `x_{m-1}`
on the two incomparable diagonals.  The `≥` half of each diagonal is `le_inf`
of positive order facts; the `≤` half unfolds the recursion and uses the
modus-ponens `(a ⇨ b) ⊓ a ≤ b`. -/

/-- **Adjacent meet** (`m = 2k+1`): `x_{2k+1} ⊓ x_{2k+2} = x_{2k}`. -/
theorem nishimuraTerm_meet_adjacent (g : H) (k : ℕ) :
    nishimuraTerm g (2 * k + 1) ⊓ nishimuraTerm g (2 * k + 2)
      = nishimuraTerm g (2 * k) := by
  apply le_antisymm
  · match k with
    | 0 =>
        show nishimuraTerm g 1 ⊓ nishimuraTerm g 2 ≤ nishimuraTerm g 0
        simp only [nishimuraTerm]; exact le_of_eq (compl_inf_self g)
    | 1 =>
        show nishimuraTerm g 3 ⊓ nishimuraTerm g 4 ≤ nishimuraTerm g 2
        simp only [nishimuraTerm]
        rw [inf_sup_left]
        refine sup_le ?_ inf_le_right
        rw [inf_comm, inf_compl_self]; exact bot_le
    | (i + 2) =>
        show nishimuraTerm g (2 * i + 5) ⊓ nishimuraTerm g (2 * i + 6)
            ≤ nishimuraTerm g (2 * i + 4)
        have hu1 : nishimuraTerm g (2 * i + 3) ⇨ nishimuraTerm g (2 * i + 2)
            = nishimuraTerm g (2 * i + 5) :=
          nishimuraTerm_himp_diagonal g (n := 2 * i) (by omega)
        have hu2 : nishimuraTerm g (2 * i + 3) ⊔ nishimuraTerm g (2 * i + 4)
            = nishimuraTerm g (2 * i + 6) :=
          nishimuraTerm_join_diagonal g (n := 2 * i + 1) (by omega)
        rw [← hu1, ← hu2, inf_sup_left]
        refine sup_le ?_ inf_le_right
        exact le_trans himp_inf_le (nishimuraTerm_even_le_add_two g (by omega))
  · exact le_inf (nishimuraTerm_even_le_succ g (by omega))
      (nishimuraTerm_even_le_add_two g (by omega))

/-- **Skip meet** (`m = 2k+1`): `x_{2k+1} ⊓ x_{2k+3} = x_{2k}`. -/
theorem nishimuraTerm_meet_skip (g : H) (k : ℕ) :
    nishimuraTerm g (2 * k + 1) ⊓ nishimuraTerm g (2 * k + 3)
      = nishimuraTerm g (2 * k) := by
  apply le_antisymm
  · match k with
    | 0 =>
        show nishimuraTerm g 1 ⊓ nishimuraTerm g 3 ≤ nishimuraTerm g 0
        simp only [nishimuraTerm]; exact le_of_eq (inf_compl_self _)
    | (i + 1) =>
        show nishimuraTerm g (2 * i + 3) ⊓ nishimuraTerm g (2 * i + 5)
            ≤ nishimuraTerm g (2 * i + 2)
        have hu : nishimuraTerm g (2 * i + 3) ⇨ nishimuraTerm g (2 * i + 2)
            = nishimuraTerm g (2 * i + 5) :=
          nishimuraTerm_himp_diagonal g (n := 2 * i) (by omega)
        rw [← hu, inf_comm]; exact himp_inf_le
  · exact le_inf (nishimuraTerm_even_le_succ g (by omega))
      (nishimuraTerm_le_of g (Or.inl ⟨by omega, by omega⟩))

/-- The meet of two ladder terms with `m ≤ n` is a ladder value: `x_m` when
comparable, else the adjacent or skip meet diagonal `x_{m-1}`. -/
theorem isLadderValue_meet_le (g : H) {m n : ℕ} (hmn : m ≤ n) :
    IsLadderValue g (nishimuraTerm g m ⊓ nishimuraTerm g n) := by
  by_cases hcomp : (m % 2 = 0) ∨ (m = n) ∨ (m + 3 ≤ n)
  · have hle : nishimuraTerm g m ≤ nishimuraTerm g n := by
      rcases hcomp with he | rfl | h3
      · exact nishimuraTerm_le_of g (Or.inl ⟨he, hmn⟩)
      · exact le_refl _
      · rcases Nat.mod_two_eq_zero_or_one m with he | ho
        · exact nishimuraTerm_le_of g (Or.inl ⟨he, hmn⟩)
        · exact nishimuraTerm_le_of g (Or.inr ⟨ho, Or.inr h3⟩)
    rw [inf_eq_left.mpr hle]
    exact isLadderValue_term g m
  · have hmodd : m % 2 = 1 := by omega
    obtain ⟨k, rfl⟩ : ∃ k, m = 2 * k + 1 := ⟨m / 2, by omega⟩
    have hcase : n = 2 * k + 2 ∨ n = 2 * k + 3 := by omega
    rcases hcase with rfl | rfl
    · rw [nishimuraTerm_meet_adjacent g k]; exact isLadderValue_term g (2 * k)
    · rw [nishimuraTerm_meet_skip g k]; exact isLadderValue_term g (2 * k)

/-- **Meet closure (the RN meet table).**  The meet of two ladder terms is a
ladder value. -/
theorem isLadderValue_meet (g : H) (m n : ℕ) :
    IsLadderValue g (nishimuraTerm g m ⊓ nishimuraTerm g n) := by
  rcases le_total m n with hmn | hmn
  · exact isLadderValue_meet_le g hmn
  · rw [inf_comm]; exact isLadderValue_meet_le g hmn

/-- **Meet closure for the whole ladder set**, `⊤` included. -/
theorem isLadderValue_inf (g : H) {x y : H} (hx : IsLadderValue g x)
    (hy : IsLadderValue g y) : IsLadderValue g (x ⊓ y) := by
  rcases hx with rfl | ⟨m, rfl⟩
  · rw [top_inf_eq]; exact hy
  · rcases hy with rfl | ⟨n, rfl⟩
    · rw [inf_top_eq]; exact isLadderValue_term g m
    · exact isLadderValue_meet g m n

/-! ### The implication table

The hardest operation.  Every cell is proved against the term recursion or the
already-closed join/meet tables — never against the `Z₈` grid, whose rungs from
`x₇` up collapse.  The two scaffolding facts that need no table are the
comparable cells (`xₘ ⇨ xₙ = ⊤` when `xₘ ≤ xₙ`) and the `n = 1` column. -/

/-- **Comparable implication is `⊤`.** -/
theorem nishimuraTerm_himp_eq_top_of_le (g : H) {m n : ℕ}
    (h : nishimuraTerm g m ≤ nishimuraTerm g n) :
    nishimuraTerm g m ⇨ nishimuraTerm g n = ⊤ :=
  himp_eq_top_iff.mpr h

/-- **The `n = 1` column.**  For `m ≥ 2` (where `g ≤ xₘ`), `xₘ ⇨ x₁ = x₁`.
Both `xₘ` and the target `x₁ = ¬g` sit so that the relative pseudocomplement
collapses back onto `¬g`: `≥` is `le_himp`, and `≤` follows because
`(xₘ ⇨ ¬g) ⊓ g ≤ ¬g ⊓ g = ⊥` (using `g ≤ xₘ` and modus ponens). -/
theorem nishimuraTerm_himp_one (g : H) {m : ℕ} (hm : 2 ≤ m) :
    nishimuraTerm g m ⇨ nishimuraTerm g 1 = nishimuraTerm g 1 := by
  have hg : g ≤ nishimuraTerm g m :=
    nishimuraTerm_le_of g (a := 2) (b := m) (Or.inl ⟨by decide, hm⟩)
  show nishimuraTerm g m ⇨ gᶜ = gᶜ
  have key : (nishimuraTerm g m ⇨ gᶜ) ⊓ g = ⊥ := by
    apply le_antisymm _ bot_le
    have hge : (nishimuraTerm g m ⇨ gᶜ) ⊓ g ≤ gᶜ :=
      le_trans (inf_le_inf_left _ hg) himp_inf_le
    calc (nishimuraTerm g m ⇨ gᶜ) ⊓ g ≤ g ⊓ gᶜ := le_inf inf_le_right hge
      _ = ⊥ := inf_compl_self g
  apply le_antisymm
  · have h := le_himp_iff.mpr (le_of_eq key)
    rwa [himp_bot] at h
  · exact le_himp

/-! #### Recursion rewrites for the implication induction

Two kernel-checked identities that turn an implication into a strictly simpler
one.  A wrong relation here cannot typecheck, so these are safe foundations for
the closure: the odd rung is itself an implication (curry the target down), and
the even rung is a meet of the two rungs above it (split the target). -/

/-- **Odd rung as an implication** (recursion): `x_{2k+3} = x_{2k+1} ⇨ x_{2k}`. -/
theorem nishimuraTerm_odd_eq_himp (g : H) (k : ℕ) :
    nishimuraTerm g (2 * k + 3) = nishimuraTerm g (2 * k + 1) ⇨ nishimuraTerm g (2 * k) := by
  match k with
  | 0 => exact nishimuraTerm_three_eq g
  | (j + 1) =>
      show nishimuraTerm g (2 * j + 5)
          = nishimuraTerm g (2 * j + 3) ⇨ nishimuraTerm g (2 * j + 2)
      exact (nishimuraTerm_himp_diagonal g (n := 2 * j) (by omega)).symm

/-- **Even rung as a meet** (the adjacent-meet diagonal, reversed):
`x_{2k} = x_{2k+1} ⊓ x_{2k+2}`. -/
theorem nishimuraTerm_even_eq_meet (g : H) (k : ℕ) :
    nishimuraTerm g (2 * k) = nishimuraTerm g (2 * k + 1) ⊓ nishimuraTerm g (2 * k + 2) :=
  (nishimuraTerm_meet_adjacent g k).symm

/-- **Odd-target reduction.**  `xₘ ⇨ x_{2k+3}` curries to `(xₘ ⊓ x_{2k+1}) ⇨ x_{2k}`;
since `xₘ ⊓ x_{2k+1}` is a ladder value, the result is a ladder value provided
implication into the strictly lower target `x_{2k}` already is. -/
theorem isLadderValue_himp_odd (g : H) (k m : ℕ)
    (ih : ∀ j, IsLadderValue g (nishimuraTerm g j ⇨ nishimuraTerm g (2 * k))) :
    IsLadderValue g (nishimuraTerm g m ⇨ nishimuraTerm g (2 * k + 3)) := by
  rw [nishimuraTerm_odd_eq_himp, himp_himp]
  rcases isLadderValue_meet g m (2 * k + 1) with h | ⟨j, hj⟩
  · rw [h, top_himp]; exact isLadderValue_term g (2 * k)
  · rw [hj]; exact ih j

/-- **Even-target reduction.**  `xₘ ⇨ x_{2k}` distributes over the meet
`x_{2k} = x_{2k+1} ⊓ x_{2k+2}`, so it is a ladder value once implication into
the two rungs above it is. -/
theorem isLadderValue_himp_even (g : H) (k m : ℕ)
    (ihodd : IsLadderValue g (nishimuraTerm g m ⇨ nishimuraTerm g (2 * k + 1)))
    (iheven : IsLadderValue g (nishimuraTerm g m ⇨ nishimuraTerm g (2 * k + 2))) :
    IsLadderValue g (nishimuraTerm g m ⇨ nishimuraTerm g (2 * k)) := by
  rw [nishimuraTerm_even_eq_meet, himp_inf_distrib]
  exact isLadderValue_inf g ihodd iheven

/-- **The `n = m+1` diagonal of the `m`-odd / `n`-even region.**  For `m` odd,
`xₘ ⇨ xₘ₊₁ = xₘ₊₂`.  Both halves use modus ponens: `≤` rewrites
`xₘ₊₂ = xₘ ⇨ xₘ₋₁` (odd recursion) and reduces to
`(xₘ ⇨ xₘ₊₁) ⊓ xₘ = xₘ ⊓ xₘ₊₁ = xₘ₋₁` (adjacent meet); `≥` reduces to
`xₘ₋₁ ≤ xₘ₊₁` (`even ≤ +2`). -/
theorem nishimuraTerm_himp_succ_odd (g : H) {m : ℕ} (hm : m % 2 = 1) :
    nishimuraTerm g m ⇨ nishimuraTerm g (m + 1) = nishimuraTerm g (m + 2) := by
  obtain ⟨i, rfl⟩ : ∃ i, m = 2 * i + 1 := ⟨m / 2, by omega⟩
  show nishimuraTerm g (2 * i + 1) ⇨ nishimuraTerm g (2 * i + 2)
      = nishimuraTerm g (2 * i + 3)
  rw [nishimuraTerm_odd_eq_himp]
  apply le_antisymm
  · rw [le_himp_iff]
    calc (nishimuraTerm g (2 * i + 1) ⇨ nishimuraTerm g (2 * i + 2))
            ⊓ nishimuraTerm g (2 * i + 1)
        ≤ nishimuraTerm g (2 * i + 1) ⊓ nishimuraTerm g (2 * i + 2) :=
          le_inf inf_le_right himp_inf_le
      _ = nishimuraTerm g (2 * i) := nishimuraTerm_meet_adjacent g i
  · rw [le_himp_iff]
    exact le_trans himp_inf_le (nishimuraTerm_even_le_add_two g (by omega))

end NormalForm

end FalseWork.Lattice
