/-
Copyright (c) 2026 Chris Brink. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Brink

# The converse of the all-n law is FALSE
(deeper-theorem item 1 of 2026-06-10; pre-registered in
`validation/claims/unique-ordinary-structure.md`)

The all-n kernel law (`nishimura_ordinary_unique`) says: if a Heyting
algebra is one-generated by an ordinary element, that element is its
unique ordinary element.  The natural converse — *a finite Heyting algebra
with a unique ordinary element is one-generated by it* — would have made
uniqueness of the forced kernel *characterize* logic's one-generated
objects, strengthening the weld.

**It is false.**  This file kernel-checks the minimal counterexample:

* **`H8`** is the 8-element downset lattice of the 5-element poset
  `0 < 1 < 3 < 4`, `2 < 3` (found by exhaustive enumeration of all finite
  distributive lattices of cardinality ≤ 12, `scripts/unique-ordinary-search.py`;
  the *minimality* of 8 rests on that enumeration — tag [C]; the
  counterexample itself is [K] below).
* **Citkin's construction (pers. comm., 2026-06-11):** the same algebra arises
  as **`Z_6 + Z_3`** — glue a 3-element chain Heyting algebra atop the
  6-element one-generated algebra `Z_6` (= `Div12` by Theorem 6 [C]). Citkin
  confirmed the 8-element minimality of the converse failure and verified the
  smallest-dense-element lemma (`a ⊔ ¬a` is least dense when `a` is the unique
  ordinary element). Lean isomorphism `H8 ≅ Z_6 + Z_3` pre-registered [O] in
  `validation/claims/unique-ordinary-structure.md` §4c.
* `H8.ordinary_unique` [K]: `a` is the unique ordinary element of `H8`
  (so `a` is also the unique non-degenerate four-cell kernel,
  `H8.kernel_unique`).
* `H8.not_nishimura_generated` [K]: `H8` is **not** Nishimura-generated by
  `a` — the term ladder in `a` never reaches the dense element `d`.
  Mechanism: the seven elements `≠ d` form a Heyting subalgebra containing
  `a` (checked by `decide`), and term values cannot leave a subalgebra
  containing the generator (`nishimuraTerm_mem_of_closed`, general).
* Combined with Nishimura's theorem **[C]** ("every one-generated Heyting
  algebra is enumerated by the Nishimura terms in its generator"), `H8` is
  not one-generated *at all*: a generator would be ordinary
  (`|H8| = 8 ≥ 6`, Citkin Prop. 4(c)), hence equal to `a` by
  `nishimura_ordinary_unique` — but `H8` is not generated by `a`.

**The instructive contrast**: `Z_8` (in `NishimuraTruncations.lean`) and
`H8` both have eight elements and a unique ordinary element.  `Z_8` is
one-generated; `H8` is not.  Uniqueness of the kernel does **not** imply
the algebra is logic's object — "unique ordinary element" and
"one-generated" are independent facts, and the weld (`Div12 ≅ Z_6`) needs
both, established separately, as they were.

## The salvage lemma (general [K])

What *does* survive of the converse: in any Heyting algebra with unique
ordinary element `a`, the dense elements are exactly the filter above
`a ⊔ ¬a` (`unique_ordinary_dense_iff`).  Proof via the trichotomy: for
dense `x`, the element `a ⊓ x` is neither regular nor dense, hence
ordinary, hence `= a`; similarly `¬a ⊓ x` is forced to be regular `= ¬a`.
(A stronger hand-conjecture from the same session — that unique
ordinariness forces the regular skeleton to be `2²` — was *refuted during
the session* by a 10-element example with skeleton `2³`; see the
validation claim.  The dense-filter lemma is the part that survived.)
-/
import Mathlib.Order.Heyting.Basic
import Mathlib.Data.Fintype.Card
import FalseWorkPapers.Examples.NishimuraKernelLaw

namespace FalseWork.Lattice

/-! ## 1. General lemma: Nishimura terms cannot leave a closed predicate -/

section Closed

variable {H : Type*} [HeytingAlgebra H]

/-- **Term values live in any subalgebra containing the generator.**  If a
predicate `P` holds at `⊥` and at `g` and is closed under `ᶜ`, `⊔`, `⇨`,
then it holds at every Nishimura term value in `g`.  This is the engine
for *non*-generation proofs: exhibit a proper closed predicate containing
`g`, and every element outside it is unreachable. -/
theorem nishimuraTerm_mem_of_closed (P : H → Prop) (g : H)
    (hbot : P ⊥) (hg : P g) (hcompl : ∀ x, P x → P xᶜ)
    (hsup : ∀ x y, P x → P y → P (x ⊔ y))
    (himp : ∀ x y, P x → P y → P (x ⇨ y)) :
    ∀ n, P (nishimuraTerm g n) := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    rcases n with - | - | - | - | - | m
    · simpa [nishimuraTerm] using hbot
    · simpa [nishimuraTerm] using hcompl g hg
    · simpa [nishimuraTerm] using hg
    · simpa [nishimuraTerm] using hcompl _ (hcompl g hg)
    · simpa [nishimuraTerm] using hsup _ _ (hcompl g hg) hg
    · by_cases hm0 : m % 2 = 0
      · rw [show nishimuraTerm g (m + 5)
            = nishimuraTerm g (m + 3) ⇨ nishimuraTerm g (m + 2) from by
          simp [nishimuraTerm, hm0]]
        exact himp _ _ (ih (m + 3) (by omega)) (ih (m + 2) (by omega))
      · have hm1 : m % 2 = 1 := by omega
        rw [show nishimuraTerm g (m + 5)
            = nishimuraTerm g (m + 2) ⊔ nishimuraTerm g (m + 3) from by
          simp [nishimuraTerm, hm1]]
        exact hsup _ _ (ih (m + 2) (by omega)) (ih (m + 3) (by omega))

end Closed

/-! ## 2. The salvage lemma: dense elements form the filter above `a ⊔ ¬a` -/

section Salvage

variable {H : Type*} [HeytingAlgebra H]

/-- For dense `x` (`¬x = ⊥`), meeting with `x` does not change complements:
`¬(b ⊓ x) = ¬b`. -/
private lemma compl_inf_dense {x : H} (hx : xᶜ = ⊥) (b : H) :
    (b ⊓ x)ᶜ = bᶜ := by
  refine le_antisymm ?_ (compl_anti inf_le_left)
  have h1 : (b ⊓ x)ᶜ ⊓ (b ⊓ x) ≤ ⊥ := by
    rw [inf_comm]; exact (inf_compl_self _).le
  have h2 : ((b ⊓ x)ᶜ ⊓ b) ⊓ x ≤ ⊥ := by rwa [inf_assoc]
  have h3 : (b ⊓ x)ᶜ ⊓ b ≤ xᶜ :=
    le_compl_iff_disjoint_right.mpr (disjoint_iff_inf_le.mpr h2)
  rw [hx] at h3
  exact le_compl_iff_disjoint_right.mpr (disjoint_iff_inf_le.mpr h3)

/-- **The salvage lemma [K].**  In a Heyting algebra whose unique ordinary
element is `a`, an element is dense **iff** it lies above `a ⊔ ¬a`: the
dense elements are exactly the principal filter `↑(a ⊔ ¬a)`, so the least
dense element exists and equals `a ⊔ ¬a` (the fourth Nishimura term).
This is what survives of the refuted converse: uniqueness does not force
one-generation, but it pins the dense part to the generator's excluded
middle. -/
theorem unique_ordinary_dense_iff (a : H)
    (hu : ∀ b : H, IsOrdinary b ↔ b = a) (x : H) :
    xᶜ = ⊥ ↔ a ⊔ aᶜ ≤ x := by
  obtain ⟨h2, h1⟩ : IsOrdinary a := (hu a).mpr rfl
  have ha0 : a ≠ ⊥ := by
    rintro rfl
    exact h2 (by rw [compl_bot, compl_top])
  constructor
  · intro hx
    -- `a ⊓ x` is neither regular nor dense, hence ordinary, hence `= a`.
    have hA : (a ⊓ x)ᶜ = aᶜ := compl_inf_dense hx a
    have hordA : IsOrdinary (a ⊓ x) := by
      constructor
      · rw [show (a ⊓ x)ᶜᶜ = aᶜᶜ from congrArg (·ᶜ) hA]
        intro he
        exact h2 (le_antisymm (he ▸ inf_le_left) le_compl_compl)
      · rw [hA]; exact h1
    have hax : a ≤ x := inf_eq_left.mp ((hu _).mp hordA)
    -- `¬a ⊓ x` cannot be ordinary (it would equal `a`, forcing `a = ⊥`)
    -- and cannot be dense (its complement is `¬¬a ≥ a > ⊥`), so it is
    -- regular, which forces `¬a ⊓ x = ¬¬¬a = ¬a`, i.e. `¬a ≤ x`.
    have hB : (aᶜ ⊓ x)ᶜ = aᶜᶜ := compl_inf_dense hx aᶜ
    by_cases hreg : (aᶜ ⊓ x)ᶜᶜ = aᶜ ⊓ x
    · rw [show (aᶜ ⊓ x)ᶜᶜ = aᶜ from by
        rw [show (aᶜ ⊓ x)ᶜᶜ = aᶜᶜᶜ from congrArg (·ᶜ) hB, compl_compl_compl]]
        at hreg
      exact sup_le hax (inf_eq_left.mp hreg.symm)
    · exfalso
      have hordB : IsOrdinary (aᶜ ⊓ x) := by
        refine ⟨hreg, ?_⟩
        rw [hB]
        intro hcc
        exact ha0 (le_bot_iff.mp (le_compl_compl.trans hcc.le))
      have heq : aᶜ ⊓ x = a := (hu _).mp hordB
      have haa : a ≤ aᶜ := heq.symm.trans_le inf_le_left
      have hbot : a ≤ a ⊓ aᶜ := le_inf le_rfl haa
      rw [inf_compl_self] at hbot
      exact ha0 (le_bot_iff.mp hbot)
  · intro hge
    have : xᶜ ≤ (a ⊔ aᶜ)ᶜ := compl_anti hge
    rw [compl_sup] at this
    exact le_bot_iff.mp (this.trans (inf_compl_self _).le)

end Salvage

/-! ## 3. `H8`: the minimal counterexample

The downset lattice of the poset `P = {0 < 1 < 3 < 4, 2 < 3}` (five
elements, five join-irreducibles).  Elements named by their downsets:

| name  | downset       | role                                   |
|-------|---------------|----------------------------------------|
| `bot` | `∅`           | `⊥`                                    |
| `a`   | `{0}`         | the unique ordinary element            |
| `n`   | `{2}`         | `¬a` (regular)                         |
| `r`   | `{0,1}`       | `¬¬a` (regular)                        |
| `an`  | `{0,2}`       | `a ⊔ ¬a` — least dense (salvage lemma) |
| `rn`  | `{0,1,2}`     | `¬¬a ⊔ (a ⊔ ¬a)` — dense               |
| `d`   | `{0,1,2,3}`   | dense, **unreachable from `a`**        |
| `top` | `{0,1,2,3,4}` | `⊤`                                    |

The term ladder in `a` stabilizes after seven values (`x₅ = ¬¬a ⇨ a = an`
falls back onto `x₄`, then `x₆ = rn`, then `⊤`); `d` is join-irreducible
and dense, so no meet, join, implication, or negation of reachable
elements produces it. -/

namespace Examples

inductive H8 : Type
  | bot | a | n | r | an | rn | d | top
  deriving DecidableEq, Repr

namespace H8

instance : Fintype H8 :=
  ⟨{bot, a, n, r, an, rn, d, top}, by intro x; cases x <;> decide⟩

/-- Order = subset order on downsets. -/
def leb : H8 → H8 → Bool
  | bot, _    => true
  | a,   a    => true
  | a,   r    => true
  | a,   an   => true
  | a,   rn   => true
  | a,   d    => true
  | a,   top  => true
  | n,   n    => true
  | n,   an   => true
  | n,   rn   => true
  | n,   d    => true
  | n,   top  => true
  | r,   r    => true
  | r,   rn   => true
  | r,   d    => true
  | r,   top  => true
  | an,  an   => true
  | an,  rn   => true
  | an,  d    => true
  | an,  top  => true
  | rn,  rn   => true
  | rn,  d    => true
  | rn,  top  => true
  | d,   d    => true
  | d,   top  => true
  | top, top  => true
  | _,   _    => false

instance : LE H8 := ⟨fun x y => leb x y = true⟩
instance : LT H8 := ⟨fun x y => x ≤ y ∧ ¬ y ≤ x⟩

instance decLE : ∀ x y : H8, Decidable (x ≤ y) := fun x y => by
  show Decidable (leb x y = true); exact decEq _ _

instance : DecidableLE H8 := decLE

def meet : H8 → H8 → H8
  | bot, _   => bot
  | _,   bot => bot
  | top, y   => y
  | x,   top => x
  | a,   a   => a
  | a,   n   => bot
  | a,   r   => a
  | a,   an  => a
  | a,   rn  => a
  | a,   d   => a
  | n,   a   => bot
  | n,   n   => n
  | n,   r   => bot
  | n,   an  => n
  | n,   rn  => n
  | n,   d   => n
  | r,   a   => a
  | r,   n   => bot
  | r,   r   => r
  | r,   an  => a
  | r,   rn  => r
  | r,   d   => r
  | an,  a   => a
  | an,  n   => n
  | an,  r   => a
  | an,  an  => an
  | an,  rn  => an
  | an,  d   => an
  | rn,  a   => a
  | rn,  n   => n
  | rn,  r   => r
  | rn,  an  => an
  | rn,  rn  => rn
  | rn,  d   => rn
  | d,   a   => a
  | d,   n   => n
  | d,   r   => r
  | d,   an  => an
  | d,   rn  => rn
  | d,   d   => d

def join : H8 → H8 → H8
  | bot, y   => y
  | x,   bot => x
  | top, _   => top
  | _,   top => top
  | a,   a   => a
  | a,   n   => an
  | a,   r   => r
  | a,   an  => an
  | a,   rn  => rn
  | a,   d   => d
  | n,   a   => an
  | n,   n   => n
  | n,   r   => rn
  | n,   an  => an
  | n,   rn  => rn
  | n,   d   => d
  | r,   a   => r
  | r,   n   => rn
  | r,   r   => r
  | r,   an  => rn
  | r,   rn  => rn
  | r,   d   => d
  | an,  a   => an
  | an,  n   => an
  | an,  r   => rn
  | an,  an  => an
  | an,  rn  => rn
  | an,  d   => d
  | rn,  a   => rn
  | rn,  n   => rn
  | rn,  r   => rn
  | rn,  an  => rn
  | rn,  rn  => rn
  | rn,  d   => d
  | d,   a   => d
  | d,   n   => d
  | d,   r   => d
  | d,   an  => d
  | d,   rn  => d
  | d,   d   => d

instance : Min H8 := ⟨meet⟩
instance : Max H8 := ⟨join⟩
instance : Top H8 := ⟨top⟩
instance : Bot H8 := ⟨bot⟩

/-- `x ⇨ y` = largest downset `z` with `↓p ∩ x ⊆ y` for all `p ∈ z`. -/
def himpFun : H8 → H8 → H8
  | bot, _   => top
  | top, y   => y
  | a,   bot => n
  | a,   a   => top
  | a,   n   => n
  | a,   r   => top
  | a,   an  => top
  | a,   rn  => top
  | a,   d   => top
  | a,   top => top
  | n,   bot => r
  | n,   a   => r
  | n,   n   => top
  | n,   r   => r
  | n,   an  => top
  | n,   rn  => top
  | n,   d   => top
  | n,   top => top
  | r,   bot => n
  | r,   a   => an
  | r,   n   => n
  | r,   r   => top
  | r,   an  => an
  | r,   rn  => top
  | r,   d   => top
  | r,   top => top
  | an,  bot => bot
  | an,  a   => r
  | an,  n   => n
  | an,  r   => r
  | an,  an  => top
  | an,  rn  => top
  | an,  d   => top
  | an,  top => top
  | rn,  bot => bot
  | rn,  a   => a
  | rn,  n   => n
  | rn,  r   => r
  | rn,  an  => an
  | rn,  rn  => top
  | rn,  d   => top
  | rn,  top => top
  | d,   bot => bot
  | d,   a   => a
  | d,   n   => n
  | d,   r   => r
  | d,   an  => an
  | d,   rn  => rn
  | d,   d   => top
  | d,   top => top

instance : HImp H8 := ⟨himpFun⟩
instance : Compl H8 := ⟨fun x => himpFun x bot⟩

instance : PartialOrder H8 where
  le := (· ≤ ·)
  lt := (· < ·)
  le_refl       := fun x       => by cases x <;> decide
  le_trans      := fun x y z   => by cases x <;> cases y <;> cases z <;> decide
  le_antisymm   := fun x y     => by cases x <;> cases y <;> decide
  lt_iff_le_not_ge := fun _ _  => Iff.rfl

instance : SemilatticeInf H8 where
  inf           := (· ⊓ ·)
  inf_le_left   := fun x y     => by cases x <;> cases y <;> decide
  inf_le_right  := fun x y     => by cases x <;> cases y <;> decide
  le_inf        := fun x y z   => by cases x <;> cases y <;> cases z <;> decide

instance : SemilatticeSup H8 where
  sup           := (· ⊔ ·)
  le_sup_left   := fun x y     => by cases x <;> cases y <;> decide
  le_sup_right  := fun x y     => by cases x <;> cases y <;> decide
  sup_le        := fun x y z   => by cases x <;> cases y <;> cases z <;> decide

instance : Lattice H8 where
  __ := (inferInstance : SemilatticeInf H8)
  __ := (inferInstance : SemilatticeSup H8)

instance : DistribLattice H8 where
  le_sup_inf    := fun x y z   => by cases x <;> cases y <;> cases z <;> decide

instance : BoundedOrder H8 where
  top := top
  bot := bot
  le_top x := by cases x <;> decide
  bot_le x := by cases x <;> decide

theorem le_himp_iff_h8 (x y z : H8) : x ≤ y ⇨ z ↔ x ⊓ y ≤ z := by
  cases x <;> cases y <;> cases z <;> decide

instance heytingAlgebra : HeytingAlgebra H8 :=
  HeytingAlgebra.ofHImp himpFun le_himp_iff_h8

/-- Cardinality 8 — the same as `Z_8`, for the contrast. -/
theorem card : Fintype.card H8 = 8 := rfl

/-- **`a` is the unique ordinary element of `H8`** (exhaustive).  The same
uniqueness that the all-n law derives for `Z_n` from one-generation holds
here — but, as `not_nishimura_generated` shows, *without* one-generation. -/
theorem ordinary_unique : ∀ x : H8, IsOrdinary x ↔ x = a := by
  unfold IsOrdinary; decide

/-- The partition form: `a` is the unique four-cell kernel of `H8`. -/
theorem kernel_unique : ∀ x : H8, AllFourCellsInhabited x ↔ x = a := by
  decide

/-- The salvage lemma's content, checked concretely: the dense elements of
`H8` are exactly those above `a ⊔ ¬a = an`. -/
theorem dense_filter : ∀ x : H8, xᶜ = ⊥ ↔ a ⊔ aᶜ ≤ x := by decide

/-- **`H8` is not Nishimura-generated by its unique ordinary element.**
The seven elements `≠ d` satisfy a closed predicate containing `a`, so no
Nishimura term in `a` evaluates to `d`.  By Nishimura's theorem **[C]**
(one-generated ⟹ Nishimura-enumerated by the generator) plus
`nishimura_ordinary_unique` (any ordinary generator would have to be `a`),
`H8` is not one-generated at all.  **The converse of the all-n law is
false.** -/
theorem not_nishimura_generated :
    ¬ (∀ y : H8, y = ⊤ ∨ ∃ m : ℕ, y = nishimuraTerm a m) := by
  intro h
  rcases h d with hd | ⟨m, hd⟩
  · exact absurd hd (by decide)
  · have hmem : nishimuraTerm a m ≠ d :=
      nishimuraTerm_mem_of_closed (fun x : H8 => x ≠ d) a
        (by decide) (by decide)
        (fun x => by revert x; decide)
        (fun x y => by revert x y; decide)
        (fun x y => by revert x y; decide) m
    exact hmem hd.symm

end H8

/-- **Headline bundle: the converse of the all-n law is false [K].**
`H8` has a unique ordinary element (equivalently, a unique non-degenerate
four-cell kernel) yet is not Nishimura-generated by it.  Uniqueness of the
forced kernel does not characterize one-generated Heyting algebras: the
weld's two ingredients — unique kernel and one-generation — are logically
independent. -/
theorem unique_ordinary_converse_false :
    (∀ x : H8, IsOrdinary x ↔ x = H8.a) ∧
    ¬ (∀ y : H8, y = ⊤ ∨ ∃ m : ℕ, y = nishimuraTerm H8.a m) :=
  ⟨H8.ordinary_unique, H8.not_nishimura_generated⟩

end Examples

end FalseWork.Lattice
