"""Exhaustive search: finite Heyting algebras with a unique ordinary element
that are NOT one-generated by it.

Scope: ALL finite Heyting algebras of cardinality <= MAX_SIZE.  By Birkhoff
duality every finite distributive lattice (= finite Heyting algebra) is the
downset lattice D(P) of a finite poset P (its join-irreducibles), so the
search over posets P with |D(P)| <= MAX_SIZE is complete for this scope.

Poset generation: incremental.  Every finite poset arises by repeatedly
adding a new element whose strict down-set is a downset of the poset built
so far (add elements along any linear extension).  This generates each poset
at least once (duplicates are harmless for a completeness argument) and the
downset count is monotone under element addition, so pruning at
|D(P)| > MAX_SIZE is sound.

For each lattice D(P):
  * ordinary elements:  S with  ~S != bottom  and  ~~S != S
    (~S = {p : down(p) & S = {}} — pseudocomplement in D(P));
  * if exactly one ordinary element a exists, compute the Heyting closure
    of {a} under meet, join, ->, bottom and compare with D(P).

Pre-registered in validation/claims/unique-ordinary-structure.md (section 3,
check 2) BEFORE this script first ran.
"""

import sys
from itertools import combinations

MAX_SIZE = 12  # max lattice cardinality |D(P)|


def downsets(downs):
    """All downsets of the poset given as list of down-set bitmasks
    (downs[i] = bitmask of elements <= i, including i)."""
    n = len(downs)
    result = []
    for mask in range(1 << n):
        ok = True
        for i in range(n):
            if (mask >> i) & 1 and (downs[i] & mask) != downs[i]:
                ok = False
                break
        if ok:
            result.append(mask)
    return result


def analyze(downs):
    """Return (size, unique_ordinary_flag, one_generated_flag_or_None)."""
    n = len(downs)
    dsets = downsets(downs)
    size = len(dsets)
    full = (1 << n) - 1

    def neg(s):
        out = 0
        for p in range(n):
            if downs[p] & s == 0:
                out |= 1 << p
        # intersect characteristic downset: out is automatically a downset
        return out

    def himp(s, t):
        out = 0
        for p in range(n):
            if downs[p] & s & ~t == 0:
                out |= 1 << p
        return out

    ordinary = [s for s in dsets if neg(s) != 0 and neg(neg(s)) != s]
    if len(ordinary) != 1:
        return size, False, None
    a = ordinary[0]

    # Heyting closure of {a}
    closure = {0, a, full}
    frontier = True
    while frontier:
        frontier = False
        items = list(closure)
        for x in items:
            for y in items:
                for z in (x & y, x | y, himp(x, y)):
                    if z not in closure:
                        closure.add(z)
                        frontier = True
    return size, True, len(closure) == size


def main():
    found = []          # (lattice size, poset downs) counterexamples
    unique_total = 0
    lattices_seen = 0
    # stack of posets: each poset is a tuple of down-masks
    stack = [()]
    seen_posets = set()
    while stack:
        downs = stack.pop()
        if downs in seen_posets:
            continue
        seen_posets.add(downs)
        dsets = downsets(list(downs))
        if len(dsets) > MAX_SIZE:
            continue
        if downs:
            lattices_seen += 1
            size, uniq, onegen = analyze(list(downs))
            if uniq:
                unique_total += 1
                if not onegen:
                    found.append((size, downs))
        # extend: new element with strict-down-set = any downset of current
        i = len(downs)
        for d in dsets:
            new = downs + (d | (1 << i),)
            # canonicalize cheaply: sort by down-mask popcount then value is
            # NOT a true canonical form; rely on seen_posets for exact dups
            stack.append(new)

    print(f"posets explored (incl. label-duplicates): {len(seen_posets)}")
    print(f"lattices analyzed (with duplicates): {lattices_seen}")
    print(f"lattices with a unique ordinary element: {unique_total}")
    if found:
        sizes = sorted(set(s for s, _ in found))
        print(f"counterexample lattice sizes found: {sizes}")
        print(f"MINIMAL counterexample cardinality: {min(sizes)}")
        # print one witness per minimal size
        m = min(sizes)
        for s, downs in found:
            if s == m:
                print(f"  witness poset down-masks: {[bin(d) for d in downs]}")
                break
    else:
        print("NO counterexample with |H| <=", MAX_SIZE,
              "- conjecture survives this scope")


if __name__ == "__main__":
    sys.setrecursionlimit(10000)
    main()
