/-
Copyright (c) 2026 Chris Brink.
Released under the same license as the rest of the FalseWork Papers.

Authors: Chris Brink (FalseWork)

# Canonization closure: the structural effects of Commitment-yes

This file formalizes the *closure layer* of the framework's
canonization apparatus, as developed in
`preprints/four-position-partition/closure-canonization.md`.

The classification layer (`Partition.lean`) answers: which of four
structural cells does a morphism inhabit? The Commitment gate layer
(`CommitmentGate.lean`) answers: within a cell, is a morphism at
the cell's structural limit? This file opens a third question:

> What are the **structural consequences** of a morphism being
> Commitment-yes for the rest of the morphism space?

The thesis of the closure framework is: a Commitment-yes morphism
`f` at position `P` generates a *reflective subcategory* of the
ambient topos, that reflection induces an idempotent monad and
hence (by the bridge in `SpencerBrown.lean`) a distinction structure,
and the four-position partition theorem applied to this *induced*
distinction structure produces a recursive secondary classification
of every morphism in the topos. Subsequent works are then positioned
both globally (in the original partition) and relative to the
canonized figure (in the induced partition).

## What this file provides

* `CanonizationClosure Δ f` — a structure type carrying the data of
  a candidate canonization closure for `f` relative to `Δ`. Fields:
  an idempotent monad `T` on `C`, a witness `μ_iso` that the
  multiplication is a natural isomorphism. The structure is the
  *data* of a candidate; the predicate identifying *which* monads
  count as canonization closures of `f` is open mathematical work
  (cf. §5 of the companion document).

* `CanonizationClosure.inducedDistinction` — given a canonization-
  closure witness, the induced distinction structure on `C` via
  `DistinctionStructure.ofIdempotentMonad`.

* `recursive_partition` — the conditional recursive partition
  theorem. Given a canonization-closure witness for `f`, the four-
  position partition theorem applies to the induced distinction
  structure. Every morphism in `C` with non-trivial induced-D-image
  is classified into one of four cells relative to the canonization
  figure.

## What this file deliberately does NOT provide

* A predicate `Generates Δ f T` identifying *which* idempotent monads
  count as canonization closures of `f`. Three candidate predicates
  are surveyed in the companion document; selecting one is an open
  mathematical and historical decision the framework has not yet
  made. The Lean structure is agnostic between candidates: an
  instance of `CanonizationClosure` carries the data, and a future
  refinement would add a `Generates` field.

* A construction of `CanonizationClosure` for any specific morphism.
  The framework's empirical canon-formation work (Bach, Coltrane,
  Schoenberg as commitment-yes figures in their respective cells)
  is interpretive; a formal closure data for these figures has not
  been constructed.

* Iteration of the recursion. The recursive partition theorem
  applies once; canonization closures of canonization closures
  (third-order classification) are not formalized here.

## Cross-reference

* `preprints/four-position-partition/closure-canonization.md` — the
  companion document developing the closure framework in prose; this
  file is its mechanized counterpart.
* `preprints/four-position-partition/paper.md` — the underlying
  partition theorem this file builds on.
* `Positions/SpencerBrown.lean` — `DistinctionStructure.ofIdempotentMonad`,
  the bridge from idempotent monads to distinction structures used by
  `inducedDistinction`.
* `Positions/Partition.lean` — `four_position_partition`, the
  underlying classification theorem applied recursively.
* `Positions/CommitmentGate.lean` — the binary fixedness condition
  that *triggers* the closure layer for a morphism; the closure layer
  assumes commitment-yes as input and operates on its consequences.
-/

import FalseWorkPapers.Positions.Setup
import FalseWorkPapers.Positions.Partition
import FalseWorkPapers.Positions.SpencerBrown
import FalseWorkPapers.Positions.CommitmentGate

namespace FalseWork.Positions

open CategoryTheory CategoryTheory.Limits

universe v u

variable {C : Type u} [Category.{v} C]

/-! ## The canonization closure -/

/-- A *canonization-closure witness* for a morphism `f : X ⟶ Y`
relative to a distinction structure `Δ` carries the data of an
idempotent monad `T` on the ambient category, intended to represent
the reflective subcategory generated by `f` as a canonization figure.

The structure intentionally does **not** include a predicate
identifying *which* monads count as canonization closures of `f`.
That predicate — `Generates Δ f T` — is left open as the load-
bearing mathematical question of the framework. Three candidate
specifications are surveyed in
`preprints/four-position-partition/closure-canonization.md` §5:

1. `T` is the smallest idempotent monad on `C` whose Eilenberg-Moore
   category contains `Y` (closure-by-codomain).
2. `T` is the smallest idempotent monad on `C` such that `f` factors
   through some morphism in the Eilenberg-Moore category (closure-
   by-factorization).
3. `T` arises as a colimit of cell-restricted iterations applied to
   `f`'s structural orbit (closure-by-iteration-colimit).

Each candidate has tradeoffs and the framework's empirical work on
canon formation has not yet selected between them.

The `Δ` and `f` parameters are carried in the type signature even
though they are not used in the data; this leaves room for a future
refinement to add a `Generates Δ f T` field linking them. -/
structure CanonizationClosure (Δ : DistinctionStructure C)
    {X Y : C} (_f : X ⟶ Y) where
  /-- The idempotent monad representing the canonization closure. -/
  T : Monad C
  /-- The monad's multiplication is a natural isomorphism — i.e.,
  the monad is idempotent in the sense matching the bridge in
  `SpencerBrown.lean`. -/
  μ_iso : IsIso T.μ

namespace CanonizationClosure

/-- The distinction structure on `C` induced by a canonization-
closure witness. Direct application of
`DistinctionStructure.ofIdempotentMonad` (cf. `SpencerBrown.lean`,
Remark 5.5 of the paper) to the bundled monad.

The induced distinction structure has the canonization figure's
closure as its kernel image: morphisms in the topos are classified
relative to the territory the canonization figure has organized,
rather than relative to the original distinction structure `Δ`.

The four cells of the partition theorem, when applied to this
induced structure, become the *Sub-Infrastructure*, *Sub-Distribution*,
*Sub-Exploitation*, *Sub-Refusal* of the closure framework — the
secondary classification of every morphism relative to the
canonization axis. -/
noncomputable def inducedDistinction
    {Δ : DistinctionStructure C} {X Y : C} {f : X ⟶ Y}
    (cc : CanonizationClosure Δ f) : DistinctionStructure C :=
  letI : IsIso cc.T.μ := cc.μ_iso
  DistinctionStructure.ofIdempotentMonad cc.T

end CanonizationClosure

/-! ## The recursive partition theorem (conditional on closure) -/

section RecursivePartition

variable [HasImages C] [HasPullbacks C] [HasSubobjectClassifier C]
  [HasEqualizers C] [HasInitial C] [HasBinaryCoproducts C] [InitialMonoClass C]

/-- **Recursive partition theorem (conditional).** Given a canonization-
closure witness `cc` for `f` relative to `Δ`, the four-position
partition theorem applies to the induced distinction structure
`cc.inducedDistinction`. Every morphism `g : A ⟶ B` with non-trivial
`cc.inducedDistinction`-D-image falls into exactly one of the four
cells (`IsInfrastructure`, `IsDistribution`, `IsExploitation`,
`IsRefusal`) computed *relative to* the canonization closure.

This is the recursive classification of morphisms in `C` against the
canonization axis: each morphism receives a second four-cell position
in addition to its original position under `Δ`. Sub-Infrastructure
of the original cell at the canonization axis are morphisms whose
canonized-closure-image lies inside the closure's kernel image
(territorially captured by the canonized figure); Sub-Refusal are
morphisms whose image lies in the strict complement (operating
outside the territory); Sub-Distribution and Sub-Exploitation occupy
the straddling and closure-residue regions respectively.

The theorem is a direct application of `four_position_partition`
(`Partition.lean`) to `cc.inducedDistinction`. The substantive
content is therefore *the existence and identification of the
canonization-closure witness*, not the partition itself. This file
records the conditional theorem as a named result and clarifies
its dependence on the closure data.

**What this theorem does not say.** It does not say which morphisms
admit canonization-closure witnesses, nor under what hypotheses such
witnesses exist, nor that the witness is unique. Those are the open
mathematical questions of the closure framework (cf.
`preprints/four-position-partition/closure-canonization.md` §9).
The conditional theorem says only: *if* the closure data is
provided, *then* the recursive partition operates as expected. -/
theorem recursive_partition
    {Δ : DistinctionStructure C} {X Y : C} {f : X ⟶ Y}
    (cc : CanonizationClosure Δ f)
    {A B : C} (g : A ⟶ B)
    (h_nontriv :
      Subobject.mk (image.ι (cc.inducedDistinction.D.map g)) ≠ ⊥) :
    (IsInfrastructure cc.inducedDistinction g ∨
      IsDistribution cc.inducedDistinction g ∨
      IsExploitation cc.inducedDistinction g ∨
      IsRefusal cc.inducedDistinction g) ∧
    (IsInfrastructure cc.inducedDistinction g →
      ¬ IsDistribution cc.inducedDistinction g) ∧
    (IsInfrastructure cc.inducedDistinction g →
      ¬ IsExploitation cc.inducedDistinction g) ∧
    (IsInfrastructure cc.inducedDistinction g →
      ¬ IsRefusal cc.inducedDistinction g) ∧
    (IsDistribution cc.inducedDistinction g →
      ¬ IsExploitation cc.inducedDistinction g) ∧
    (IsDistribution cc.inducedDistinction g →
      ¬ IsRefusal cc.inducedDistinction g) ∧
    (IsExploitation cc.inducedDistinction g →
      ¬ IsRefusal cc.inducedDistinction g) :=
  four_position_partition cc.inducedDistinction g h_nontriv

end RecursivePartition

/-! ## The generator refinement (the resolution layer)

The closure layer specifies the *region* of structural reach a
canonization figure has within the ambient topos. A natural
refinement adds the condition that, *within that region*, the figure
also acts as a *resolving instrument* — distinctions among later
morphisms become legible through composition with maps out of the
canonization codomain. This is the Spencer-Brown "measuring
instrument" intuition (§5 of the closure-canonization companion
document) formalized as the standard categorical *separator* condition.

An object `G` in a category `C` is a separator if morphisms in `C`
are determined by their composition with maps out of `G`: for any
parallel pair `g₁, g₂ : A ⟶ B`, if `h ≫ g₁ = h ≫ g₂` for every
`h : G ⟶ A`, then `g₁ = g₂`. Equivalently (contrapositively), maps
out of `G` distinguish any pair of distinct parallel morphisms.

The generator refinement says: a canonization-yes-with-resolution
figure `f : X ⟶ Y` is one that admits a canonization closure
*and* whose codomain `Y` is a separator for the ambient category.
The two conditions together capture the full canonization
phenomenon: the closure gives the region, the separator condition
gives the resolution within the region.

Unlike the closure's `Generates` predicate (left open in `§5` of the
companion document), the separator condition is mathematically
standard and concretely formalizable today. The conditional
separation theorem below is therefore *unconditional* in form
(the proof is a direct unfolding of the separator definition),
while the question of *which `f` admit canonization-generator
witnesses* remains open empirical/historical work. -/

/-- A *canonization-generator witness* refines a canonization-closure
witness with the additional condition that the codomain `Y` of `f`
acts as a separator for the ambient category `C`. This is the
formalization of the "measuring instrument" intuition: within the
territory the canonization closure organizes, the canonization
figure's codomain resolves equality among morphisms.

The two-layer canonization-yes definition (closure + separator) is
intended to capture the full historical canonization phenomenon:
the closure gives the structural territory the figure organizes,
and the separator condition gives the figure's role as a measuring
instrument within that territory. Cf.
`preprints/four-position-partition/closure-canonization.md` §5a. -/
structure CanonizationGenerator (Δ : DistinctionStructure C)
    {X Y : C} (f : X ⟶ Y) extends CanonizationClosure Δ f where
  /-- The codomain `Y` is a separator for `C`: parallel morphisms in
  `C` agreeing under all post-composition with maps out of `Y` are
  themselves equal. This is the standard categorical separator
  condition. -/
  isSeparator : ∀ {A B : C} (g₁ g₂ : A ⟶ B),
    (∀ h : Y ⟶ A, h ≫ g₁ = h ≫ g₂) → g₁ = g₂

/-- **Conditional separation theorem.** Given a canonization-
generator witness, parallel morphisms in `C` are determined by their
composition with maps out of the canonization codomain `Y`. This is
the Spencer-Brown "measuring instrument" content of canonization
formalized: the canonization figure's codomain resolves distinctions
among morphisms.

The proof is direct: the separation condition is the defining
property of the separator. This theorem packages the property into
a named result connecting it explicitly to the canonization-generator
witness data.

**Relationship to the closure layer.** The closure layer's
`recursive_partition` theorem classifies morphisms relative to the
canonization closure. The generator layer's separation theorem says
that, within the same canonization data, equality of morphisms is
detectable from the canonization codomain. The two are independent
consequences of the same canonization-generator data: classification
+ resolution. -/
theorem canonization_separation
    {Δ : DistinctionStructure C} {X Y : C} {f : X ⟶ Y}
    (cg : CanonizationGenerator Δ f)
    {A B : C} (g₁ g₂ : A ⟶ B)
    (h_agree : ∀ h : Y ⟶ A, h ≫ g₁ = h ≫ g₂) :
    g₁ = g₂ :=
  cg.isSeparator g₁ g₂ h_agree

/-! ## Cross-layer connection: Commitment-yes ⇒ canonization-generator witness

The framework's three layers of canonization (classification,
Commitment gate, closure/generator) are formally distinct. The
classification layer (`Partition.lean`) is theorem-grade and
unconditional. The Commitment-gate layer (`CommitmentGate.lean`) is
schema-grade: its predicate `IsCommitmentYes` has a uniform shape
across cells but its content is held as four open per-cell iteration
operators (currently placeholders). The closure/generator layer
(this file) is conditional: the recursive partition and separation
theorems fire given canonization-generator data, but identifying
*which* morphisms admit such witnesses is open.

The cross-layer connection — that being Commitment-yes is the
structural source of canonization-generator witnesses — is the
framework's intended architectural claim. The conditional theorem
below records this connection at the type-level: a Commitment-yes
morphism with a separator codomain admits a canonization-generator
witness. The witness here is the trivial identity-monad
construction (cf. `Examples/CanonizationGeneratorInstance.lean`),
which means:

* The theorem's proof does *not* use the commitment hypothesis. The
  commitment predicate is currently `True` (placeholder), so any
  hypothesis dependence would be vacuous. The hypothesis is carried
  in the signature so that, when `IsCommitmentYes` is filled in with
  cell-specific iteration content, the theorem will become
  substantive without requiring a signature change.

* The theorem produces *some* canonization-generator witness, not
  necessarily the *empirical* canonization closure (which would be a
  reflective subcategory of the ambient topos, not the identity
  monad). The framework's empirical claim — that Bach's canonization
  closure is the tonal-counterpoint reflective subcategory, etc. —
  is *not* asserted by this theorem. The empirical content remains
  open future work, cf. the closure-canonization companion document.

The theorem is therefore honest in the same sense as
`IsCommitmentYes`: the structural connection is in place, the
content is open. The framework commits to the *shape* of the
cross-layer alignment without committing to either layer's open
substantive content.

Cf. `preprints/four-position-partition/closure-canonization.md` §8b
for the structural reading of this theorem. -/

section CrossLayer

variable {C : Type u} [Category.{v} C]

/-- **Cross-layer alignment (conditional).** If a morphism `f : X ⟶ Y`
is `IsCommitmentYes` at some cell `P` relative to a distinction
structure `Δ`, and `Y` is a separator for `C`, then `f` admits a
`CanonizationGenerator` witness relative to `Δ`.

The witness produced here is the trivial identity-monad construction:
`T := Monad.id C`, `μ_iso := IsIso.id _`. This is the always-available
witness in any category. The theorem's structural content is the
*signature*, which records the cross-layer dependency
(commitment-yes ⇒ generator-witness exists) even though the current
proof does not use the commitment hypothesis (because
`IsCommitmentYes` is currently a placeholder `True`; see
`CommitmentGate.lean`).

When `IsCommitmentYes` is filled in with per-cell iteration content,
this theorem will become substantive: it will assert that a
non-trivially-Commitment-yes morphism admits *some* generator
witness (and may then be refined to assert that it admits a
structurally specific witness reflecting the cell's iteration
content). The current form is the framework's commitment to the
shape of the cross-layer connection.

**What the trivial witness does and does not buy.** It buys
*kernel-checked type inhabitation of the conclusion under the stated
hypotheses* — a real (if currently trivial) implication theorem
linking the two layers. It does *not* buy the structurally-correct
empirical canonization closure for any specific Commitment-yes
morphism; that remains open empirical/historical work.

Cf. `preprints/four-position-partition/closure-canonization.md` §8b. -/
def CanonizationGenerator.ofCommitmentYes
    (Δ : DistinctionStructure C) (P : Cell) {X Y : C} (f : X ⟶ Y)
    (_h_commit : IsCommitmentYes Δ P f)
    (h_sep : ∀ {A B : C} (g₁ g₂ : A ⟶ B),
      (∀ h : Y ⟶ A, h ≫ g₁ = h ≫ g₂) → g₁ = g₂) :
    CanonizationGenerator Δ f where
  T := Monad.id C
  μ_iso := by
    show IsIso (𝟙 (𝟭 C))
    exact IsIso.id _
  isSeparator := h_sep

/-- Existential-form companion to `CanonizationGenerator.ofCommitmentYes`.
Sometimes useful as the propositional form of the cross-layer claim
(e.g., when downstream consumers need only the existence and not the
specific witness). -/
theorem commitment_yes_admits_canonization_generator
    (Δ : DistinctionStructure C) (P : Cell) {X Y : C} (f : X ⟶ Y)
    (h_commit : IsCommitmentYes Δ P f)
    (h_sep : ∀ {A B : C} (g₁ g₂ : A ⟶ B),
      (∀ h : Y ⟶ A, h ≫ g₁ = h ≫ g₂) → g₁ = g₂) :
    Nonempty (CanonizationGenerator Δ f) :=
  ⟨CanonizationGenerator.ofCommitmentYes Δ P f h_commit h_sep⟩

end CrossLayer

/-! ## Status

DONE (kernel-checkable in this file):
* `CanonizationClosure` — the structure type carrying canonization-
  closure data (idempotent monad + iso witness for multiplication).
* `CanonizationClosure.inducedDistinction` — distinction structure
  induced via the `SpencerBrown.lean` bridge.
* `recursive_partition` — the conditional recursive partition
  theorem. Direct application of `four_position_partition` to the
  induced distinction structure. Proof is one-line composition.
* `CanonizationGenerator` — refinement of the closure structure
  with the separator condition on the canonization codomain.
* `canonization_separation` — the conditional separation theorem.
  Direct application of the separator condition. Proof is a one-
  line unfolding of the definition.
* `CanonizationGenerator.ofCommitmentYes` — the cross-layer
  alignment definition: a Commitment-yes morphism with a separator
  codomain admits a canonization-generator witness (the trivial
  identity-monad construction). Records the framework's cross-layer
  architectural claim at the type level even though the current
  proof does not use the commitment hypothesis (because
  `IsCommitmentYes` is currently a `True` placeholder).
* `commitment_yes_admits_canonization_generator` — propositional
  companion (`Nonempty (CanonizationGenerator Δ f)`).

NOT FORMALIZED HERE (open framework work):
* The `Generates Δ f T` predicate identifying which idempotent
  monads count as canonization closures of `f`. Three candidates
  surveyed in `closure-canonization.md` §5; selection deferred
  pending substantive mathematical and historical work.
* A construction of `CanonizationClosure` (or `CanonizationGenerator`)
  for any specific morphism. The framework's empirical canon-
  formation work has not yet been lifted to formal closure
  constructions.
* Existence and uniqueness theorems for canonization closures under
  the framework's elementary-topos hypothesis bundle. Open.
* Iteration of the recursion (closures of closures producing third-
  order classification). The recursive partition theorem applies
  once here; multi-level recursion is left as a possible future
  direction.

WHY THE CONDITIONAL FORM IS HONEST:
Both conditional theorems (`recursive_partition` and
`canonization_separation`) are mathematically trivial given the
existing infrastructure. The recursive partition is a one-line
composition of `DistinctionStructure.ofIdempotentMonad` and
`four_position_partition`. The separation theorem is a one-line
unfolding of the separator definition. The substantive contribution
of this file is therefore not the proofs themselves but the
*identification of the right objects* (`CanonizationClosure`,
`CanonizationGenerator`) on which to apply existing infrastructure,
and the *separation* of the conditional theorems (which the
framework gives once the data is provided) from the open
constructions (which the framework does not yet provide). The
mathematical work is concentrated in (a) specifying the `Generates`
predicate for the closure layer and (b) verifying for specific
morphisms that they admit closure-with-separator witnesses; this
file deliberately leaves both as open.

ARCHITECTURE — THE THREE LAYERS OF CANONIZATION:
The framework's canonization apparatus is now organized into three
layers, each addressing a structurally distinct question:

| Layer            | Question                          | File               |
|------------------|-----------------------------------|--------------------|
| Classification   | Which cell?                       | Partition.lean     |
| Commitment gate  | At cell's structural limit?       | CommitmentGate.lean|
| Closure/Generator| Consequences for the rest of C?   | this file          |

The closure component of the third layer gives the structural
territory the canonization figure organizes (the recursive
partition); the generator component gives the figure's resolving
behaviour within that territory (the separation theorem). The two
components together are intended to capture the full canonization
phenomenon. Connection to the Commitment gate (the predicate that
*triggers* canonization for a given morphism) is now formally
recorded by `CanonizationGenerator.ofCommitmentYes`: commitment-yes
plus separator codomain implies the canonization-generator structure
type is inhabited. The cross-layer claim is therefore established
*at the level of inhabitation*; what remains open is the empirical
content of "the right witness" — the actual reflective subcategory
generated by a specific Commitment-yes figure — and the substantive
content of `IsCommitmentYes` itself.

CONNECTION TO `CommitmentGate.lean`:
The closure/generator layer is conceptually downstream of the
Commitment gate: the gate identifies *which* morphisms are
commitment-yes (binary fixedness in cell-restricted iteration); the
closure/generator layer identifies *what such morphisms generate
and resolve* (a reflective subcategory, the recursive partition,
the separation theorem). The two layers are structurally distinct
and currently formalized at different levels — the gate at schema
level with placeholder content (`IsCommitmentYes := True`), the
closure/generator layer at conditional theorem level. The cross-
layer alignment definition `CanonizationGenerator.ofCommitmentYes`
records the architectural connection between them in kernel-checked
form: under the framework's intended reading, every Commitment-yes
morphism with a separator codomain admits a canonization-generator
witness. The substantive open work is twofold: (a) fill in the per-
cell iteration content of `IsCommitmentYes` so the commitment
hypothesis carries information; (b) refine the cross-layer
construction so the witness it produces is the *empirically correct*
canonization closure (a reflective subcategory of the ambient
topos), not the trivial identity-monad one. Both are deferred as
substantive future work.
-/

end FalseWork.Positions
