/-
Copyright (c) 2026 Chris Brink.
Released under the same license as the rest of the FalseWork Papers.

Authors: Chris Brink (FalseWork)

# Canonization closure: the structural effects of Commitment-yes

This file formalizes the *closure layer* of the framework's
canonization apparatus, as developed in
`preprints/four-position-partition/closure-canonization.md`.

The classification layer (`Partition.lean`) answers: which of four
structural cells does a morphism inhabit? The Commitment gate layer
(`CommitmentGate.lean`) answers: within a cell, is a morphism at
the cell's structural limit? This file opens a third question:

> What are the **structural consequences** of a morphism being
> Commitment-yes for the rest of the morphism space?

The thesis of the closure framework is: a Commitment-yes morphism
`f` at position `P` generates a *reflective subcategory* of the
ambient topos, that reflection induces an idempotent monad and
hence (by the bridge in `SpencerBrown.lean`) a distinction structure,
and the four-position partition theorem applied to this *induced*
distinction structure produces a recursive secondary classification
of every morphism in the topos. Subsequent works are then positioned
both globally (in the original partition) and relative to the
canonized figure (in the induced partition).

## What this file provides

* `CanonizationClosure Δ f` — a structure type carrying the data of
  a candidate canonization closure for `f` relative to `Δ`. Fields:
  an idempotent monad `T` on `C`, a witness `μ_iso` that the
  multiplication is a natural isomorphism. The structure is the
  *data* of a candidate; the predicate identifying *which* monads
  count as canonization closures of `f` is open mathematical work
  (cf. §5 of the companion document).

* `CanonizationClosure.inducedDistinction` — given a canonization-
  closure witness, the induced distinction structure on `C` via
  `DistinctionStructure.ofIdempotentMonad`.

* `recursive_partition` — the conditional recursive partition
  theorem. Given a canonization-closure witness for `f`, the four-
  position partition theorem applies to the induced distinction
  structure. Every morphism in `C` with non-trivial induced-D-image
  is classified into one of four cells relative to the canonization
  figure.

## What this file deliberately does NOT provide

* A predicate `Generates Δ f T` identifying *which* idempotent monads
  count as canonization closures of `f`. Three candidate predicates
  are surveyed in the companion document; selecting one is an open
  mathematical and historical decision the framework has not yet
  made. The Lean structure is agnostic between candidates: an
  instance of `CanonizationClosure` carries the data, and a future
  refinement would add a `Generates` field.

* A construction of `CanonizationClosure` for any specific morphism.
  The framework's empirical canon-formation work (Bach, Coltrane,
  Schoenberg as commitment-yes figures in their respective cells)
  is interpretive; a formal closure data for these figures has not
  been constructed.

* Iteration of the recursion. The recursive partition theorem
  applies once; canonization closures of canonization closures
  (third-order classification) are not formalized here.

## Cross-reference

* `preprints/four-position-partition/closure-canonization.md` — the
  companion document developing the closure framework in prose; this
  file is its mechanized counterpart.
* `preprints/four-position-partition/paper.md` — the underlying
  partition theorem this file builds on.
* `Positions/SpencerBrown.lean` — `DistinctionStructure.ofIdempotentMonad`,
  the bridge from idempotent monads to distinction structures used by
  `inducedDistinction`.
* `Positions/Partition.lean` — `four_position_partition`, the
  underlying classification theorem applied recursively.
* `Positions/CommitmentGate.lean` — the binary fixedness condition
  that *triggers* the closure layer for a morphism; the closure layer
  assumes commitment-yes as input and operates on its consequences.
-/

import FalseWorkPapers.Positions.Setup
import FalseWorkPapers.Positions.Partition
import FalseWorkPapers.Positions.SpencerBrown

namespace FalseWork.Positions

open CategoryTheory CategoryTheory.Limits

universe v u

variable {C : Type u} [Category.{v} C]

/-! ## The canonization closure -/

/-- A *canonization-closure witness* for a morphism `f : X ⟶ Y`
relative to a distinction structure `Δ` carries the data of an
idempotent monad `T` on the ambient category, intended to represent
the reflective subcategory generated by `f` as a canonization figure.

The structure intentionally does **not** include a predicate
identifying *which* monads count as canonization closures of `f`.
That predicate — `Generates Δ f T` — is left open as the load-
bearing mathematical question of the framework. Three candidate
specifications are surveyed in
`preprints/four-position-partition/closure-canonization.md` §5:

1. `T` is the smallest idempotent monad on `C` whose Eilenberg-Moore
   category contains `Y` (closure-by-codomain).
2. `T` is the smallest idempotent monad on `C` such that `f` factors
   through some morphism in the Eilenberg-Moore category (closure-
   by-factorization).
3. `T` arises as a colimit of cell-restricted iterations applied to
   `f`'s structural orbit (closure-by-iteration-colimit).

Each candidate has tradeoffs and the framework's empirical work on
canon formation has not yet selected between them.

The `Δ` and `f` parameters are carried in the type signature even
though they are not used in the data; this leaves room for a future
refinement to add a `Generates Δ f T` field linking them. -/
structure CanonizationClosure (Δ : DistinctionStructure C)
    {X Y : C} (_f : X ⟶ Y) where
  /-- The idempotent monad representing the canonization closure. -/
  T : Monad C
  /-- The monad's multiplication is a natural isomorphism — i.e.,
  the monad is idempotent in the sense matching the bridge in
  `SpencerBrown.lean`. -/
  μ_iso : IsIso T.μ

namespace CanonizationClosure

/-- The distinction structure on `C` induced by a canonization-
closure witness. Direct application of
`DistinctionStructure.ofIdempotentMonad` (cf. `SpencerBrown.lean`,
Remark 5.5 of the paper) to the bundled monad.

The induced distinction structure has the canonization figure's
closure as its kernel image: morphisms in the topos are classified
relative to the territory the canonization figure has organized,
rather than relative to the original distinction structure `Δ`.

The four cells of the partition theorem, when applied to this
induced structure, become the *Sub-Infrastructure*, *Sub-Distribution*,
*Sub-Exploitation*, *Sub-Refusal* of the closure framework — the
secondary classification of every morphism relative to the
canonization axis. -/
noncomputable def inducedDistinction
    {Δ : DistinctionStructure C} {X Y : C} {f : X ⟶ Y}
    (cc : CanonizationClosure Δ f) : DistinctionStructure C :=
  letI : IsIso cc.T.μ := cc.μ_iso
  DistinctionStructure.ofIdempotentMonad cc.T

end CanonizationClosure

/-! ## The recursive partition theorem (conditional on closure) -/

section RecursivePartition

variable [HasImages C] [HasPullbacks C] [HasSubobjectClassifier C]
  [HasEqualizers C] [HasInitial C] [HasBinaryCoproducts C] [InitialMonoClass C]

/-- **Recursive partition theorem (conditional).** Given a canonization-
closure witness `cc` for `f` relative to `Δ`, the four-position
partition theorem applies to the induced distinction structure
`cc.inducedDistinction`. Every morphism `g : A ⟶ B` with non-trivial
`cc.inducedDistinction`-D-image falls into exactly one of the four
cells (`IsInfrastructure`, `IsDistribution`, `IsExploitation`,
`IsRefusal`) computed *relative to* the canonization closure.

This is the recursive classification of morphisms in `C` against the
canonization axis: each morphism receives a second four-cell position
in addition to its original position under `Δ`. Sub-Infrastructure
of the original cell at the canonization axis are morphisms whose
canonized-closure-image lies inside the closure's kernel image
(territorially captured by the canonized figure); Sub-Refusal are
morphisms whose image lies in the strict complement (operating
outside the territory); Sub-Distribution and Sub-Exploitation occupy
the straddling and closure-residue regions respectively.

The theorem is a direct application of `four_position_partition`
(`Partition.lean`) to `cc.inducedDistinction`. The substantive
content is therefore *the existence and identification of the
canonization-closure witness*, not the partition itself. This file
records the conditional theorem as a named result and clarifies
its dependence on the closure data.

**What this theorem does not say.** It does not say which morphisms
admit canonization-closure witnesses, nor under what hypotheses such
witnesses exist, nor that the witness is unique. Those are the open
mathematical questions of the closure framework (cf.
`preprints/four-position-partition/closure-canonization.md` §9).
The conditional theorem says only: *if* the closure data is
provided, *then* the recursive partition operates as expected. -/
theorem recursive_partition
    {Δ : DistinctionStructure C} {X Y : C} {f : X ⟶ Y}
    (cc : CanonizationClosure Δ f)
    {A B : C} (g : A ⟶ B)
    (h_nontriv :
      Subobject.mk (image.ι (cc.inducedDistinction.D.map g)) ≠ ⊥) :
    (IsInfrastructure cc.inducedDistinction g ∨
      IsDistribution cc.inducedDistinction g ∨
      IsExploitation cc.inducedDistinction g ∨
      IsRefusal cc.inducedDistinction g) ∧
    (IsInfrastructure cc.inducedDistinction g →
      ¬ IsDistribution cc.inducedDistinction g) ∧
    (IsInfrastructure cc.inducedDistinction g →
      ¬ IsExploitation cc.inducedDistinction g) ∧
    (IsInfrastructure cc.inducedDistinction g →
      ¬ IsRefusal cc.inducedDistinction g) ∧
    (IsDistribution cc.inducedDistinction g →
      ¬ IsExploitation cc.inducedDistinction g) ∧
    (IsDistribution cc.inducedDistinction g →
      ¬ IsRefusal cc.inducedDistinction g) ∧
    (IsExploitation cc.inducedDistinction g →
      ¬ IsRefusal cc.inducedDistinction g) :=
  four_position_partition cc.inducedDistinction g h_nontriv

end RecursivePartition

/-! ## Status

DONE (kernel-checkable in this file):
* `CanonizationClosure` — the structure type carrying canonization-
  closure data (idempotent monad + iso witness for multiplication).
* `CanonizationClosure.inducedDistinction` — distinction structure
  induced via the `SpencerBrown.lean` bridge.
* `recursive_partition` — the conditional recursive partition
  theorem. Direct application of `four_position_partition` to the
  induced distinction structure. Proof is one-line composition.

NOT FORMALIZED HERE (open framework work):
* The `Generates Δ f T` predicate identifying which idempotent
  monads count as canonization closures of `f`. Three candidates
  surveyed in `closure-canonization.md` §5; selection deferred
  pending substantive mathematical and historical work.
* A construction of `CanonizationClosure` for any specific morphism.
  The framework's empirical canon-formation work has not yet been
  lifted to formal closure constructions.
* Existence and uniqueness theorems for canonization closures under
  the framework's elementary-topos hypothesis bundle. Open.
* Iteration of the recursion (closures of closures producing third-
  order classification). The recursive partition theorem applies
  once here; multi-level recursion is left as a possible future
  direction.

WHY THE CONDITIONAL FORM IS HONEST:
The recursive partition theorem is mathematically trivial given the
existing bridge in `SpencerBrown.lean` and the partition theorem in
`Partition.lean` — it composes them. The substantive contribution
of this file is therefore not the *proof* of the recursive partition,
but the *identification of the right object* (`CanonizationClosure`)
on which to apply existing infrastructure. The framework's
mathematical work is concentrated in specifying the `Generates`
predicate, which this file deliberately leaves open.

CONNECTION TO `CommitmentGate.lean`:
The closure layer is conceptually downstream of the Commitment gate:
the gate identifies *which* morphisms are commitment-yes (binary
fixedness in cell-restricted iteration); the closure layer
identifies *what such morphisms generate* (a reflective subcategory
and the recursive partition). The two layers are structurally
distinct and currently formalized at different levels — the gate at
schema level with placeholder content, the closure layer at
conditional theorem level. Bringing them into structural alignment
(e.g., showing that commitment-yes morphisms automatically admit
canonization closures of a specific form) is a substantial open
problem.
-/

end FalseWork.Positions
